---
name: kolourpaint
confinement: strict
grade: stable
base: core20
adopt-info: kolourpaint
apps:
    kolourpaint:
        extensions:
        - kde-neon
        common-id: org.kde.kolourpaint.desktop
        command: usr/bin/kolourpaint
        plugs:
        - home
        - network
        - network-bind
        - audio-playback
        - removable-media
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    kolourpaint:
        parse-info:
        - usr/share/metainfo/org.kde.kolourpaint.appdata.xml
        plugin: cmake
        build-packages:
        - libkf5sane-dev
        - libkf5doctools-dev
        stage-packages:
        - libkf5sane5
        source: http://download.kde.org/stable/release-service/22.04.3/src/kolourpaint-22.04.3.tar.xz
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;/root/stage\\;/snap/kde-frameworks-5-96-qt-5-15-5-core20-sdk/current"
version: 20.04.3
