---
name: kalzium
confinement: strict
grade: stable
base: core20
adopt-info: kalzium
apps:
    kalzium:
        extensions:
        - kde-neon
        common-id: org.kde.kalzium.desktop
        command: usr/bin/kalzium
        plugs:
        - home
        - network
        - network-bind
        - audio-playback
        - removable-media
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    openbabel:
        plugin: cmake
        source: https://github.com/openbabel/openbabel/releases/download/openbabel-3-1-1/openbabel-3.1.1-source.tar.bz2
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$SNAPCRAFT_STAGE\\;/snap/kde-frameworks-5-98-qt-5-15-6-core20-sdk/current"
    kalzium:
        after:
        - openbabel
        parse-info:
        - usr/share/metainfo/org.kde.kalzium.appdata.xml
        plugin: cmake
        build-packages:
        - libkf5doctools-dev
        - chemical-mime-data
        - libboost-python-dev
        - libeigen3-dev
        - libfacile-ocaml-dev
        - libglew-dev
        - libkf5khtml-dev
        - libsm-dev
        - libavogadro-dev
        stage-packages:
        - chemical-mime-data
        - ocaml-nox-4.08.1
        - libglew-dev
        - libkf5khtml5
        - libsm6
        - avogadro
        - avogadro-utils
        source: http://download.kde.org/stable/release-service/22.08.1/src/kalzium-22.08.1.tar.xz
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$SNAPCRAFT_STAGE\\;/snap/kde-frameworks-5-98-qt-5-15-6-core20-sdk/current"
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/$SNAPCRAFT_ARCH_TRIPLET/6.0.0"
            - "-usr/lib/aspell/*"
        prime:
        - "$exclusion"
version: 22.08.1
