---
name: korganizer
version: 23.04.3
base: core22
adopt-info: korganizer
confinement: strict
grade: stable
apps:
    korganizer:
        # extensions:
        # - kde-neon
        common-id: org.kde.korganizer.desktop
        command: usr/bin/korganizer
        plugs:
        - desktop
        - desktop-legacy
        - opengl
        - wayland
        - x11
        - audio-playback
        - unity7
        - network
        - network-bind
        command-chain:
        - snap/command-chain/desktop-launch
assumes:
- snapd2.55.3
compression: lzo
plugs:
    desktop:
        mount-host-font-cache: false
    icon-themes:
        interface: content
        target: $SNAP/data-dir/icons
        default-provider: gtk-common-themes
    sound-themes:
        interface: content
        target: $SNAP/data-dir/sounds
        default-provider: gtk-common-themes
    kf5-5-108-qt-5-15-10-core22:
        content: kf5-5-108-qt-5-15-10-core22-all
        interface: content
        default-provider: kf5-5-108-qt-5-15-10-core22
        target: $SNAP/kf5
environment:
    SNAP_DESKTOP_RUNTIME: $SNAP/kf5
    GST_PLUGIN_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0"
    GST_PLUGIN_SYSTEM_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0"
    GST_PLUGIN_SCANNER: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner"
hooks:
    configure:
        plugs:
        - desktop
        command-chain:
        - snap/command-chain/hooks-configure-desktop
layout:
    "/usr/lib/$CRAFT_ARCH_TRIPLET/alsa-lib":
        symlink: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/alsa-lib"
    "/usr/share/alsa":
        symlink: "$SNAP/usr/share/alsa"
    /usr/share/X11:
        symlink: $SNAP/kf5/usr/share/X11
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.korganizer
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - jammy
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    kde-neon:
        source: /snap/snapcraft/current/share/snapcraft/extensions/desktop/kde-neon
        source-type: local
        plugin: make
        make-parameters:
        - PLATFORM_PLUG=kf5-5-108-qt-5-15-10-core22
        build-snaps:
        - kf5-5-108-qt-5-15-10-core22-sdk
        build-environment:
        - &id001
            PATH: /snap/kf5-5-108-qt-5-15-10-core22-sdk/current/usr/bin${PATH:+:$PATH}
        - &id002
            XDG_DATA_DIRS: $CRAFT_STAGE/usr/share:/snap/kf5-5-108-qt-5-15-10-core22-sdk/current/usr/share:/usr/share${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}
        - &id003
            XDG_CONFIG_HOME: $CRAFT_STAGE/etc/xdg:/snap/kf5-5-108-qt-5-15-10-core22-sdk/current/etc/xdg:/etc/xdg${XDG_CONFIG_HOME:+:$XDG_CONFIG_HOME}
        - &id004
            CRAFT_CMAKE_ARGS: -DCMAKE_FIND_ROOT_PATH=/snap/kf5-5-108-qt-5-15-10-core22-sdk/current${CRAFT_CMAKE_ARGS:+:$CRAFT_CMAKE_ARGS}
    korganizer:
        after:
        - kde-neon
        - grantleetheme
        - kontactinterface
        - libkdepim
        parse-info:
        - usr/share/metainfo/org.kde.korganizer.appdata.xml
        plugin: cmake
        build-packages:
        - kuserfeedback-dev
        - libassuan-dev
        - libboost-dev
        - libboost-graph-dev
        - libgpgme11-dev
        - libgrantlee5-dev
        - libkf5akonadi-dev
        - libkf5akonadicalendar-dev
        - libkf5akonadicontact-dev
        - libkf5akonadimime-dev
        - libkf5akonadinotes-dev
        - libkf5akonadisearch-dev
        - libkf5akonadiserver-dev
        - libkf5calendarcore-dev
        - libkf5calendarsupport-dev
        - libkf5calendarutils-dev
        - libkf5contacteditor-dev
        - libkf5contacts-dev
        - libkf5doctools-dev
        - libkf5grantleetheme-dev
        - libkf5holidays-dev
        - libkf5identitymanagement-dev
        - libkf5incidenceeditor-dev
        - libkf5kontactinterface-dev
        - libkf5ktextaddons-dev
        - libkf5ldap-dev
        - libkf5libkdepim-dev
        - libkf5mailcommon-dev
        - libkf5mailtransport-dev
        - libkf5messagecomposer-dev
        - libkf5mime-dev
        - libkf5mimetreeparser-dev
        - libkf5pimcommon-dev
        - libkf5pimtextedit-dev
        - libkf5templateparser-dev
        - libkpimgapi-dev
        - libphonon4qt5-dev
        - libphonon4qt5experimental-dev
        - libx11-dev
        - pkg-config
        - xsltproc
        - zlib1g-dev
        stage-packages:
                - kuserfeedback5
        - libassuan5
        - libboost1.74
        - libboost-graph1.74
        - libgpgme11
        - libgrantlee5
        - libkf5akonadicore5
        - libkf5akonadicalendar5
        - libkf5akonadicontact5
        - libkf5akonadimime5
        - libkf5akonadinotes5
        - libkf5akonadisearch5
        - libkf5akonadiserver5
        - libkf5calendarcore5
        - libkf5calendarsupport5
        - libkf5calendarutils5
        - libkf5contacteditor5
        - libkf5contacts5
        - libkf5doctools5
        - libkf5grantleetheme5
        - libkf5holidays5
        - libkf5identitymanagement5
        - libkf5incidenceeditor5
        - libkf5kontactinterface5
        - libkf5ktextaddons5
        - libkf5ldap5
        - libkf5libkdepim5
        - libkf5mailcommon5
        - libkf5mailtransport5
        - libkf5messagecomposer5
        - libkf5mime5
        - libkf5mimetreeparser5
        - libkf5pimcommon5
        - libkf5pimtextedit5
        - libkf5templateparser5
        - libkpimgapi5
        - phonon4qt5
        - phonon4qt5experimental
        - xsltproc
        - zlib1g
        source: http://download.kde.org/stable/release-service/23.04.2/src/korganizer-23.04.2.tar.xz
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - -DCMAKE_FIND_ROOT_PATH=$CRAFT_STAGE:/snap/kf5-5-106-qt-5-15-9-core22-sdk/current
        build-environment: *id005
        prime:
        - "-usr/lib/*/cmake/*"
        - "-usr/include/*"
        - "-usr/share/ECM/*"
        - "-usr/share/doc/*"
        - "-usr/share/man/*"
        - "-usr/share/icons/breeze-dark*"
        - "-usr/bin/X11"
        - "-usr/lib/gcc/$CRAFT_ARCH_TRIPLET/6.0.0"
        - "-usr/lib/aspell/*"
        - "-etc/alsa/conf.d/99-pulse.conf"
    cleanup:
        after:
        - syndication
        - grantleetheme
        - kontactinterface
        - libkdepim
        - korganizer
        plugin: nil
        override-prime: |
            set -eux
            #Unused libs found in linter
