---
name: krita
grade: stable
adopt-info: krita
base: core20
confinement: strict
apps:
    krita:
        common-id: org.kde.krita
        command: usr/bin/krita
        extensions:
        - kde-neon
        plugs:
        - home
        - network
        - network-bind
        - removable-media
        - audio-playback
layout:
    "/usr/bin/ffmpeg":
        bind-file: "$SNAP/usr/bin/ffmpeg"
parts:
    libheif:
        plugin: autotools
        source: https://github.com/strukturag/libheif.git
        source-tag: v1.7.0
        build-packages:
        - libde265-dev
        - pkg-config
        - g++
        - libx265-dev
        - libjpeg8-dev
        - libpng-dev
        stage-packages:
        - libde265-0
        - libx265-179
        - libjpeg8
        - libpng16-16
    krita:
        after:
        - libheif
        source: http://download.kde.org/stable/krita/5.0.5/krita-5.0.5.tar.gz
        plugin: cmake
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        build-packages:
        - libboost-dev
        - libboost-system-dev
        - libeigen3-dev
        - libfftw3-dev
        - libgif-dev
        - libglew-dev
        - libgsf-1-dev
        - libgsl-dev
        - libjpeg-dev
        - libopencolorio-dev
        - libopenexr-dev
        - libopenimageio-dev
        - libopenjp2-7-dev
        - libquazip5-dev
        - libraw-dev
        - libtiff-dev
        - libvc-dev
        - libx11-dev
        - libxi-dev
        - vc-dev
        - libmypaint-dev
        parse-info:
        - usr/share/metainfo/org.kde.krita.appdata.xml
        stage-packages:
        - freeglut3
        - libboost-system1.71.0
        - libfftw3-double3
        - libgif7
        - libgsl23
        - libgslcblas0
        - libilmbase24
        - libopencolorio1v5
        - libopenexr24
        - libquazip5-1
        - libraw19
        - libtinyxml2.6.2v5
        - libxi6
        - libyaml-cpp0.6
        - zlib1g
        - libmypaint-1.5-1
        - ffmpeg
        - libglu1-mesa
        - libslang2
        prime:
        - "-usr/share/fonts/*"
        - "-usr/lib/x86_64-linux-gnu/libQt5*"
        - "-usr/lib/x86_64-linux-gnu/libqt5*"
    qtctl:
        source: https://github.com/snapcrafters/qtctl.git
        plugin: cmake
        build-snaps:
        - kde-frameworks-5-91-qt-5-15-3-core20-sdk
    cleanup:
        after:
        - krita
        plugin: nil
        build-snaps:
        - core20
        - kde-frameworks-5-91-qt-5-15-3-core20-sdk
        override-prime: |
            set -eux
            for snap in "core20" "kde-frameworks-5-91-qt-5-15-3-core20-sdk"; do  # List all content-snaps and base snaps you're using here
              cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
            done
version: 5.0.5
