---
name: krita
grade: stable
adopt-info: krita
base: core20
confinement: strict
apps:
    krita:
        common-id: org.kde.krita
        command: usr/bin/krita
        extensions:
        - kde-neon
        plugs:
        - home
        - network
        - network-bind
        - removable-media
        - audio-playback
        environment:
            QML2_IMPORT_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qml"
slots:
    session-dbus-interface:
        interface: dbus
        name: org.krita.krita
        bus: session
layout:
    "/usr/bin/ffmpeg":
        symlink: "$SNAP/usr/bin/ffmpeg"
parts:
    libheif:
        plugin: autotools
        source: https://github.com/strukturag/libheif.git
        source-tag: v1.7.0
        build-packages:
        - libde265-dev
        - pkg-config
        - g++
        - libx265-dev
        - libjpeg8-dev
        - libpng-dev
        stage-packages:
        - libde265-0
        - libx265-179
        - libjpeg8
        - libpng16-16
    patches:
        plugin: dump
        source: patches/
        prime:
            - -*
    krita:
        after:
        - libheif
        - patches
        source: https://download.kde.org/stable/krita/5.1.0/krita-5.1.0.tar.xz
        plugin: cmake
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DBUILD_TESTING=OFF"
        build-packages:
        - libboost-dev
        - libboost-system-dev
        - libeigen3-dev
        - libfftw3-dev
        - libgif-dev
        - libglew-dev
        - libgsf-1-dev
        - libgsl-dev
        - libjpeg-dev
        - libopencolorio-dev
        - libopenexr-dev
        - libopenimageio-dev
        - libopenjp2-7-dev
        - libquazip5-dev
        - libraw-dev
        - libtiff-dev
        - libvc-dev
        - libx11-dev
        - libxi-dev
        - vc-dev
        - libmypaint-dev
        parse-info:
        - usr/share/metainfo/org.kde.krita.appdata.xml
        stage-packages:
        - freeglut3
        - libboost-system1.71.0
        - libfftw3-double3
        - libgif7
        - libgsl23
        - libgslcblas0
        - libilmbase24
        - libopencolorio1v5
        - libopenexr24
        - libquazip5-1
        - libraw19
        - libtinyxml2.6.2v5
        - libxi6
        - libyaml-cpp0.6
        - zlib1g
        - libmypaint-1.5-1
        - ffmpeg
        - libglu1-mesa
        - libslang2
        prime:
        - "-usr/share/fonts/*"
        - "-usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libQt5*"
        - "-usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libqt5*"
        override-pull: |
            snapcraftctl pull
            patch -p1 < $SNAPCRAFT_STAGE/krita_dont_use_native_file_chooser.patch
    cleanup:
        after:
        - krita
        plugin: nil
        build-snaps:
        - kde-frameworks-5-96-qt-5-15-5-core20
        override-prime: |
            set -eux
            for snap in "kde-frameworks-5-96-qt-5-15-5-core20"; do  # List all content-snaps you're using here
                cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" "$SNAPCRAFT_PRIME/usr/{}" \;
            done
            for CRUFT in bug lintian man; do
                rm -rf $SNAPCRAFT_PRIME/usr/share/$CRUFT
            done
            find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
            find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
