# Trigger build 2
---
name: elisa
base: core22
confinement: strict
grade: stable
adopt-info: elisa
version: 23.04.0
icon: $CRAFT_PROJECT_DIR/snap/gui/logo.png
apps:
    elisa:
        # extensions:
        # - kde-neon
        common-id: org.kde.elisa.desktop
        desktop: usr/share/applications/org.kde.elisa.desktop
        command: usr/bin/elisa
        plugs:
        - desktop
        - desktop-legacy
        - opengl
        - wayland
        - x11
        - audio-playback
        - unity7
        - network
        - network-bind
        command-chain:
        - snap/command-chain/desktop-launch
assumes:
- snapd2.43
compression: lzo
plugs:
    desktop:
        mount-host-font-cache: false
    icon-themes:
        interface: content
        target: $SNAP/data-dir/icons
        default-provider: gtk-common-themes
    sound-themes:
        interface: content
        target: $SNAP/data-dir/sounds
        default-provider: gtk-common-themes
    kf5-5-104-qt-5-15-8-core22:
        content: kf5-5-104-qt-5-15-8-core22-all
        interface: content
        default-provider: kf5-5-104-qt-5-15-8-core22
        target: $SNAP/kf5
environment:
    SNAP_DESKTOP_RUNTIME: $SNAP/kf5
    QML2_IMPORT_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/qml
    LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/elisa/:$SNAP/kf5/usr/lib/$CRAFT_ARCH_TRIPLET"
hooks:
    configure:
        plugs:
        - desktop
        command-chain:
        - snap/command-chain/hooks-configure-desktop
layout:
    /usr/share/X11:
        symlink: $SNAP/kf5/usr/share/X11
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.elisa
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - jammy
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: https://origin.archive.neon.kde.org/tmp/user-snaps
    key-server: keyserver.ubuntu.com
parts:
    kde-neon:
        source: /snap/snapcraft/current/share/snapcraft/extensions/desktop/kde-neon
        source-type: local
        plugin: make
        make-parameters:
        - PLATFORM_PLUG=kf5-5-104-qt-5-15-8-core22
        build-snaps:
        - kf5-5-104-qt-5-15-8-core22-sdk
        build-environment:
        - &id001
            PATH: /snap/kf5-5-104-qt-5-15-8-core22-sdk/current/usr/bin${PATH:+:$PATH}
        - &id002
            XDG_DATA_DIRS: $CRAFT_STAGE/usr/share:/snap/kf5-5-104-qt-5-15-8-core22-sdk/current/usr/share:/usr/share${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}
        - &id003
            LD_LIBRARY_PATH: /snap/kf5-5-104-qt-5-15-8-core22-sdk/current/lib/$CRAFT_ARCH_TRIPLET:/snap/kf5-5-104-qt-5-15-8-core22-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET:/snap/kf5-5-104-qt-5-15-8-core22-sdk/current/usr/lib:/snap/kf5-5-104-qt-5-15-8-core22-sdk/current/usr/lib/vala-current:/snap/kf5-5-104-qt-5-15-8-core22-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/pulseaudio${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
        - &id004
            PKG_CONFIG_PATH: /snap/kf5-5-104-qt-5-15-8-core22-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig:/snap/kf5-5-104-qt-5-15-8-core22-sdk/current/usr/lib/pkgconfig:/snap/kf5-5-104-qt-5-15-8-core22-sdk/current/usr/share/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
        - &id005
            ACLOCAL_PATH: /snap/kf5-5-104-qt-5-15-8-core22-sdk/current/usr/share/aclocal${ACLOCAL_PATH:+:$ACLOCAL_PATH}
        - &id006
            CRAFT_CMAKE_ARGS: -DCMAKE_FIND_ROOT_PATH=/snap/kf5-5-104-qt-5-15-8-core22-sdk/current${CRAFT_CMAKE_ARGS:+:$CRAFT_CMAKE_ARGS}
    elisa:
        after:
        - kde-neon
        parse-info:
        - usr/share/metainfo/org.kde.elisa.appdata.xml
        build-packages:
        - cmake
        - kirigami2-dev
        - libkf5doctools-dev
        stage-packages:
        - gstreamer1.0-libav
        - gstreamer1.0-plugins-ugly
        - gstreamer1.0-plugins-good
        - gstreamer1.0-plugins-base
        - gstreamer1.0-plugins-bad
        source: http://download.kde.org/stable/release-service/23.04.0/src/elisa-23.04.0.tar.xz
        plugin: cmake
        cmake-parameters:
        - -DKDE_INSTALL_USE_QT_SYS_PATHS=FALSE
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$CRAFT_STAGE\\;/snap/kf5-5-104-qt-5-15-8-core22-sdk/current"
        stage:
        - "-usr/lib/*/libharfbuzz.so*"
        prime:
        - "-usr/libexec"
        - "-usr/lib/*/cmake"
        - "-usr/include"
        - "-usr/share/ECM/*"
        - "-usr/share/pkgconfig"
        - "-usr/share/doc"
        - "-usr/share/doc-base"
        - "-usr/share/man/*"
        - "-usr/share/qlogging-categories5"
        - "-usr/share/icons/breeze-dark*"
        - "-usr/bin/X11"
        - "-usr/bin/fc*"
        - "-usr/lib/X11"
        - "-usr/lib/sasl2"
        - "-usr/lib/systemd"
        - "-usr/lib/gcc/$CRAFT_ARCH_TRIPLET/6.0.0"
        - "-usr/lib/aspell/*"
        - "-usr/share/lintian"
        build-environment: &id007
        - *id001
        - *id002
        - *id003
        - *id004
        - *id005
        - *id006
        override-build: |
            craftctl default

            sed -i "${CRAFT_PART_INSTALL}/usr/share/applications/org.kde.elisa.desktop" -e 's|Icon=elisa$|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/elisa.svg|'
    cleanup:
        after:
        - kde-neon
        - elisa
        plugin: nil
        override-prime: |
            set -eux
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libEGL_mesa.so.0.0.0'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libFLAC.so.8.3.0'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libGLX_mesa.so.0.0.0'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libGLdispatch.so.0.0.0'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libIexMath-2_5.so.25.0.6'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libIlmImfUtil-2_5.so.25.0.6'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libX11.so.6.4.0'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libXau.so.6.0.0'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libXdmcp.so.6.0.0'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libXext.so.6.4.0'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libXi.so.6.1.0'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libasyncns.so.0.3.1'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libcaca++.so.0.99.19'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libdconf.so.1.0.0'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libfaad_drm.so.2.0.0'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libflite_cmu_grapheme_lang.so.2.2'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libflite_cmu_grapheme_lex.so.2.2'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libflite_cmu_indic_lex.so.2.2'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libflite_cmu_time_awb.so.2.2'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libfontconfig.so.1.12.0'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libgraphite2.so.3.2.1'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libgstcheck-1.0.so.0.2003.0'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libgstcontroller-1.0.so.0.2003.0'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libgstinsertbin-1.0.so.0.2003.0'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libgstplayer-1.0.so.0.2003.0'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libgsttranscoder-1.0.so.0'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libicui18n.so.70.1'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libicuio.so.70.1'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libicutest.so.70.1'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libicuuc.so.70.1'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libjacknet.so.0.1.0'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libjackserver.so.0.1.0'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libmpeg2convert.so.0.0.0'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libogg.so.0.8.5'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libopus.so.0.8.0'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/liborc-test-0.4.so.0.32.0'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libpulse.so.0.24.1'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libsmime3.so'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libsndfile.so.1.0.31'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libsphinxad.so.3.0.0'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libssl3.so'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libunwind-coredump.so.0.0.0'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libunwind-ptrace.so.0.0.0'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libvorbis.so.0.4.9'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libvorbisenc.so.2.0.12'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libwayland-client.so.0.21.0'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libwayland-cursor.so.0.21.0'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libxcb.so.1.1.0'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libxkbcommon.so.0.0.0'
            rm 'usr/lib/$CRAFT_ARCH_TRIPLET/libzvbi-chains.so.0.0.0'

