---
name: elisa
confinement: strict
grade: devel
adopt-info: elisa
apps:
    elisa:
        extensions:
        - kde-neon
        common-id: org.kde.elisa.desktop
        command: usr/bin/elisa
        plugs:
        - home
        - network
        - network-bind
        - audio-playback
        environment:
            GST_PLUGIN_PATH: "$SNAP/usr/lib/x86_64-linux-gnu/gstreamer-1.0"
            GST_PLUGIN_SYSTEM_PATH: "$SNAP/usr/lib/x86_64-linux-gnu/gstreamer-1.0"
            GST_PLUGIN_SCANNER: "$SNAP/usr/lib/x86_64-linux-gnu/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner"
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.elisa
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    elisa:
        parse-info:
        - usr/share/metainfo/org.kde.elisa.appdata.xml
        stage-packages:
        - gstreamer1.0-fluendo-mp3
        - gstreamer1.0-libav
        - gstreamer1.0-audio-playback
        - gstreamer1.0-plugins-ugly
        - gstreamer1.0-plugins-good
        - gstreamer1.0-plugins-base
        - gstreamer1.0-plugins-bad
        source: kde:elisa
        source-type: git
        source-depth: 1
        plugin: cmake
        cmake-parameters:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;/usr\\;/root/stage\\;/snap/kde-frameworks-5-qt-5-15-3-core20-sdk/current"
        stage:
        - "-usr/lib/*/libharfbuzz.so*"
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/x86_64-linux-gnu/6.0.0"
            - "-usr/lib/aspell/*"
        prime:
        - "$exclusion"
version: 22.04.3
