---
name: konqueror
version: 22.04.0
confinement: strict
grade: stable
adopt-info: konqueror
apps:
    konqueror:
        extensions:
        - kde-neon
        parse-info:
        - usr/share/metainfo/org.kde.konqueror.appdata.xml
        common-id: org.kde.konqueror.desktop
        command: usr/bin/konqueror
        plugs:
        - home
        - network
        - network-bind
        - audio-playback
        - removable-media
parts:
    konqueror:
        plugin: cmake
        build-packages:
        - kdoctools-dev
        - libtidy-dev
        - libx11-dev
        source: http://download.kde.org/stable/release-service/22.04.0/src/konqueror-22.04.0.tar.xz
        configflags:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
