# This pipeline needs two secret variables:
#
# LAUNCHPAD_CREDENTIALS: 
#   Type: File
#   Source: Local snapcraft installation, @ ~/.local/share/snapcraft/provider/launchpad/credentials
#   You need to execute snapcraft remote-build once one your computer and log in with
#   the desired Launchpad user. Afterwards, copy the credentials.
#   See https://snamarkdownpartpcraft.io/docs/remote-build
# SNAPCRAFT_STORE_CREDENTIALS:
#   Type: Variable
#   Source: https://snapcraft.io/docs/snapcraft-authentication

# These are default values; you can overwrite them for each snap by specifying 
# those variables in the job itself.
# For example, you might want to build every snap on amd64, but some snaps also on arm64.
variables:
  # Restrict building for pushes to this branch
  ON_BRANCH: Neon/release 
  # Build architectures as a comma-separated list, e.g. amd64,arm64,armhf
  BUILD_FOR: amd64,arm64
  # Release to these channels after building. Provide as a comma-separated list, e.g. beta, edge
  # For testing purposes, you can push to snap branches. Syntax: edge/${branch_name}, e.g. edge/icon-fix
  RELEASE_TO: candidate
  #Which core base to build on
  CORE: core22
  #KF5 and QT5 version
  VERSION: 5-105-qt-5-15-9

# Use this template by extending it.
#
# By default, it builds if some file in its directory has changed.
# The directory from which a snap is built is either given by the job's name, e.g. 'kteatime', 
# or explicitly via the variable DIR.
# If the directory name matches the job name, you don't need to specify DIR.
#
# You can overwrite all variables, as shown above, by adding a 'variables' dict to the job.
# See the examples below for common use cases.
.snap:
  image: invent-registry.kde.org/sysadmin/ci-images/snap-builder:latest
  tags:
    - Snap
  stage: build
  rules:
    - if: $DIR == null && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $ON_BRANCH
      changes:
        - "$CI_JOB_NAME/**/*"
    - if: $DIR != null && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $ON_BRANCH
      changes:
        - "$DIR/**/*"
  before_script:
    - rm -rfv /snap/snapcraft
    - rm -rfv /snap/core22
    - apt-get update
    - apt-get dist-upgrade --yes
    - apt-get install --yes curl sudo jq squashfs-tools tzdata

    - |
        curl -L $(curl -H 'X-Ubuntu-Series: 16' 'https://api.snapcraft.io/api/v1/snaps/details/core20' | jq '.download_url' -r) --output core20.snap
    - mkdir -p /snap/core20 && unsquashfs -d /snap/core20/current core20.snap && rm core20.snap
    - |
        curl -L $(curl -H 'X-Ubuntu-Series: 16' 'https://api.snapcraft.io/api/v1/snaps/details/snapcraft' | jq '.download_url' -r) --output snapcraft.snap
    - mkdir -p /snap/snapcraft && unsquashfs -d /snap/snapcraft/current snapcraft.snap && rm snapcraft.snap
#     - rm -rfv /snap/snapcraft
#     - apt update && apt -y install jq curl squashfs-tools
#     - |
#         curl -L $(curl -s -H "Snap-Device-Series: 16" http://api.snapcraft.io/v2/snaps/info/snapcraft | jq '."channel-map" | map(select(.channel.name == "stable")) | .[0].download.url' -r) --output snapcraft.snap
# #    - |
# #        curl -L $(curl -H 'X-Ubuntu-Series: 16' 'https://api.snapcraft.io/api/v1/snaps/details/snapcraft' | jq '.download_url' -r) --output snapcraft.snap
#     - mkdir -p /snap/snapcraft && unsquashfs -d /snap/snapcraft/current snapcraft.snap && rm snapcraft.snap
#     - ls -la /snap/snapcraft/current/bin/
#     - ls -la /snap/snapcraft/current/usr/bin/
    - mkdir -p /snap/bin
    - echo "#!/bin/sh" > /snap/bin/snapcraft
    - snap_version="$(awk '/^version:/{print $2}' /snap/snapcraft/current/meta/snap.yaml)" && echo "export SNAP_VERSION=\"$snap_version\"" >> /snap/bin/snapcraft
    - echo 'exec "$SNAP/usr/bin/python3" "$SNAP/bin/snapcraft" "$@"' >> /snap/bin/snapcraft
    - cat /snap/bin/snapcraft
    - chmod +x /snap/bin/snapcraft
#     - chown --changes --recursive $USER:$USER /snap/snapcraft
#     - export SNAP_NAME="snapcraft"
#     - echo $PATH
#     - snapcraft --version
#     - $SNAP/bin/snapcraft --version
    - mkdir -p  ~/.local/share/snapcraft/provider/launchpad
    - echo -en "[1]\n" > ~/.local/share/snapcraft/provider/launchpad/credentials
    - echo -en "consumer_key = System-wide" >> ~/.local/share/snapcraft/provider/launchpad/credentials
    - echo -en ":" >> ~/.local/share/snapcraft/provider/launchpad/credentials
    - echo -en " KDE neon (piensa)\n" >> ~/.local/share/snapcraft/provider/launchpad/credentials
    - echo -en "consumer_secret = \n" >> ~/.local/share/snapcraft/provider/launchpad/credentials
    - echo -en "access_token = " >> ~/.local/share/snapcraft/provider/launchpad/credentials
    - echo -en $LAUNCHPAD_CREDENTIALS_ACCESS_TOKEN >> ~/.local/share/snapcraft/provider/launchpad/credentials
    - echo -en "\naccess_secret = " >> ~/.local/share/snapcraft/provider/launchpad/credentials
    - echo -en $LAUNCHPAD_CREDENTIALS_ACCESS_SECRET >> ~/.local/share/snapcraft/provider/launchpad/credentials
    - echo -en "\n" >> ~/.local/share/snapcraft/provider/launchpad/credentials
    - git config --global user.email "ci@invent.kde.org"
    - git config --global user.name "KDE Invent CI"
    - snap_dir="${DIR:-"$CI_JOB_NAME"}"
    - cd "$snap_dir"
  script:
    - shopt -s nullglob
    - snap_name="$(yq '.name' snapcraft.yaml)"
    - snapcraft remote-build --launchpad-accept-public-upload --build-for="$BUILD_FOR"
    - |
      for log in "$snap_name"_*.txt; do
        echo ""
        echo "$log"
        echo "============================"
        cat "$log"
        echo ""
      done
    - architectures=(${BUILD_FOR//,/ })
    - 'echo "Architectures (len: ${#architectures[@]}): ${architectures[@]}"'
    - snaps=(${snap_name}*.snap)
    - 'echo "Snaps (len: ${#snaps[@]}): ${snaps[@]}"'
    - if [ ${#architectures[@]} != ${#snaps[@]} ]; then echo "Number of produced snaps does not equal number of requested snaps" && exit 1; fi
    - for snap in *.snap; do snapcraft upload --release="$RELEASE_TO" "$snap"; done

# Use this template to build snaps with new content/sdk-snaps before the extension
# gets updated and shipped in a stable snapcraft release.
.prepone-extension-update:
  extends: .snap
  script:
#    - snapcraft expand-extensions > snapcraft-expanded.yaml
#    - mv snapcraft-expanded.yaml snapcraft.yaml
    - sed -i -e 's|kde-frameworks-5-102-qt-5-15-8-core22-sd|kf5-5-104-qt-5-15-8-core22-sdk|g' snapcraft.yaml
    - sed -i -e 's|kde-frameworks-5-102-qt-5-15-8-core22|kf5-5-104-qt-5-15-8-core22|g' snapcraft.yaml
    - sed -i -e 's|$SNAPCRAFT_EXTENSIONS_DIR/desktop|desktop|' snapcraft.yaml
#    - sed -i -e 's|#parse-info:|parse-info:|g' snapcraft.yaml
#    - sed -i -e 's|#    - usr/share/metainfo/org.kde.blinken.appdata.xml|    - usr/share/metainfo/org.kde.blinken.appdata.xml|g' snapcraft.yaml
    - cat snapcraft.yaml
    - cp -r /snap/snapcraft/current/share/snapcraft/extensions/desktop .
    - !reference [.snap, script]

.prepone-extension-update-core22:
  extends: .prepone-extension-update
  variables:
    BRANCH: Neon/release
    CORE: core22
    VERSION: 5-105-qt-5-15-9
    RELEASE_TO: beta

# Examples

.example-snap: # Build the snap in the directory '.example-snap'
  extends: .snap # Use the .snap template
  variables: # Overwrite some global defaults
    BUILD_ON: arm64,armhf # Build on arm64 and armhf, but do not build on amd64
    RELEASE_TO: edge # Release to edge

.example-snap:amd64:
  extends: .snap
  variables:
    BUILD_ON: amd64 # Only build on amd64
    DIR: path/to/some-other-dir # Build from the directory 'path/to/some-other-dir'

# A job to display revisions not yet published to stable

revision-watchdog:
  image: invent-registry.kde.org/sysadmin/ci-images/snap-builder:latest
  tags:
    - Snap
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - apt update && apt -y install jq curl
    - ./revision-watchdog.sh 2>&1 | tee revision-report.txt
    - report="$(cat revision-report.txt)"
    - echo "<html><head><title>Revision Watchdog Report</title></head><body><pre><code>${report}</code></pre></body></html>" > revision-report.html
  artifacts:
    name: report
    paths:
      - revision-report.txt
      - revision-report.html

# The snaps

# kde-frameworks:
#   extends: .snap
#   variables:
#     REPO: release
#     DISTRO: focal
#     KEY_ID: 444DABCF3667D0283F894EDDE6D4736255751E5D
#   script:
#     - apt update && apt -y install ruby software-properties-common dpkg-dev
#     - gem install insensitive_hash
#     - apt-key adv --keyserver keyserver.ubuntu.com --recv-key "${KEY_ID}"
#     - echo "deb http://archive.neon.kde.org/release focal main" > /etc/apt/sources.list.d/neon.list && echo "deb-src http://archive.neon.kde.org/release focal main" >> /etc/apt/sources.list.d/neon.list && apt update
#     - ruby atomize-debs.rb
#     - echo "Runtime snapcraft.yaml" && cat runtime/snapcraft.yaml
#     - echo "SDK snapcraft.yaml" && cat sdk/snapcraft.yaml
#     - cd runtime
#     - !reference [.snap, script]
#     - cd ../sdk
#     - !reference [.snap, script]

kde-frameworks-core22:
  extends: .snap
  variables:
    REPO: release
    DISTRO: jammy
    KEY_ID: 444DABCF3667D0283F894EDDE6D4736255751E5D
    ON_BRANCH: Neon/release
    RELEASE_TO: candidate
    CORE: core22
  script:
    - apt update && apt -y install ruby software-properties-common dpkg-dev
    - gem install insensitive_hash
    - apt-key adv --keyserver keyserver.ubuntu.com --recv-key "${KEY_ID}"
    - echo "deb http://archive.neon.kde.org/release jammy main" > /etc/apt/sources.list.d/neon.list &&
      echo "deb-src http://archive.neon.kde.org/release jammy main" > /etc/apt/sources.list.d/neon.list &&
      apt update
    - ruby atomize-debs-core22.rb
    - echo 'Foo'
    - echo "Runtime snapcraft.yaml" && cat runtime/snapcraft.yaml
    - echo "SDK snapcraft.yaml" && cat sdk/snapcraft.yaml
    - cd runtime
    - !reference [.snap, script]
    - cd ../sdk
    - !reference [.snap, script]

akregator:
  extends: .prepone-extension-update

alligator:
  extends: .prepone-extension-update

amor:
  extends: .prepone-extension-update

angelfish:
  extends: .prepone-extension-update

arianna:
  extends: .prepone-extension-update

ark:
  extends: .prepone-extension-update

artikulate:
  extends: .prepone-extension-update

audiotube:
  extends: .prepone-extension-update

blinken:
  extends: .prepone-extension-update

bomber:
  extends: .prepone-extension-update

bovo:
  extends: .prepone-extension-update

calindori:
  extends: .prepone-extension-update

calligra:
  extends: .prepone-extension-update

calligraplan:
  extends: .prepone-extension-update

cantor:
  extends: .prepone-extension-update

cervisia:
  extends: .prepone-extension-update

digikam:
  extends: .prepone-extension-update

dolphin:
  extends: .prepone-extension-update

dragon:
  extends: .prepone-extension-update

elisa:
  extends: .prepone-extension-update

filelight:
  extends: .prepone-extension-update

falkon:
  extends: .prepone-extension-update

gcompris-qt:
  extends: .prepone-extension-update

granatier:
  extends: .prepone-extension-update

gwenview:
  extends: .prepone-extension-update

haruna:
  extends: .prepone-extension-update

isoimagewriter:
  extends: .prepone-extension-update

itinerary:
  extends: .prepone-extension-update

juk:
  extends: .prepone-extension-update

k3b:
  extends: .prepone-extension-update

kaddressbook:
  extends: .prepone-extension-update

kalendar:
  extends: .prepone-extension-update

kamera:
  extends: .prepone-extension-update

kamoso:
  extends: .prepone-extension-update

kajongg:
  extends: .prepone-extension-update

kalarm:
  extends: .prepone-extension-update

kalgebra:
  extends: .prepone-extension-update

kalzium:
  extends: .prepone-extension-update

kanagram:
  extends: .prepone-extension-update

kapman:
  extends: .prepone-extension-update

kasts:
  extends: .prepone-extension-update

kate:
  extends: .prepone-extension-update

katomic:
  extends: .prepone-extension-update

kbackup:
  extends: .prepone-extension-update

kblackbox:
  extends: .prepone-extension-update

kblocks:
  extends: .prepone-extension-update

kbounce:
  extends: .prepone-extension-update

kbreakout:
  extends: .prepone-extension-update

kbruch:
  extends: .prepone-extension-update

kcachegrind:
  extends: .prepone-extension-update

kcalc:
  extends: .prepone-extension-update

kcharselect:
  extends: .prepone-extension-update

kclock:
  extends: .prepone-extension-update

kcolorchooser:
  extends: .prepone-extension-update

kcron:
  extends: .prepone-extension-update

kdebugsettings:
  extends: .prepone-extension-update

kdeconnect:
  extends: .prepone-extension-update

kdenlive:
  extends: .prepone-extension-update

kdevelop:
  extends: .prepone-extension-update

kdf:
  extends: .prepone-extension-update

kdiamond:
  extends: .prepone-extension-update

kfind:
  extends: .prepone-extension-update

kfourinline:
  extends: .prepone-extension-update

kgeography:
  extends: .prepone-extension-update

kgeotag:
  extends: .prepone-extension-update

kget:
  extends: .prepone-extension-update

kgpg:
  extends: .prepone-extension-update

kgoldrunner:
  extends: .prepone-extension-update

kgraphviewer:
  extends: .prepone-extension-update

khangman:
  extends: .prepone-extension-update

khelpcenter:
  extends: .prepone-extension-update

kid3:
  extends: .prepone-extension-update

kimagemapeditor:
  extends: .prepone-extension-update

kfind:
  extends: .prepone-extension-update

kfloppy:
  extends: .prepone-extension-update

kig:
  extends: .prepone-extension-update

kigo:
  extends: .prepone-extension-update

killbots:
  extends: .prepone-extension-update

kiriki:
  extends: .prepone-extension-update

kirigami-gallery:
  extends: .prepone-extension-update

kiten:
  extends: .prepone-extension-update

kjumpingcube:
  extends: .prepone-extension-update

kleopatra:
  extends: .prepone-extension-update

klettres:
  extends: .prepone-extension-update

klickety:
  extends: .prepone-extension-update

klines:
  extends: .prepone-extension-update

kmag:
  extends: .prepone-extension-update

kmahjongg:
  extends: .prepone-extension-update

kmail:
  extends: .prepone-extension-update

kmines:
  extends: .prepone-extension-update

kmousetool:
  extends: .prepone-extension-update

kmouth:
  extends: .prepone-extension-update

kmplot:
  extends: .prepone-extension-update

knavalbattle:
  extends: .prepone-extension-update

knetwalk:
  extends: .prepone-extension-update

knights:
  extends: .prepone-extension-update

knotes:
  extends: .prepone-extension-update

kolf:
  extends: .prepone-extension-update

kollision:
  extends: .prepone-extension-update

kolourpaint:
  extends: .prepone-extension-update

kommit:
  extends: .prepone-extension-update

kompare:
  extends: .prepone-extension-update

konsole:
  extends: .prepone-extension-update

konqueror:
  extends: .prepone-extension-update

konquest:
  extends: .prepone-extension-update

kontact:
  extends: .prepone-extension-update

kontrast:
  extends: .prepone-extension-update

konversation:
  extends: .prepone-extension-update

kopete:
  extends: .prepone-extension-update

korganizer:
  extends: .prepone-extension-update

kpat:
  extends: .prepone-extension-update

krdc:
  extends: .prepone-extension-update

kreversi:
  extends: .prepone-extension-update

krecorder:
  extends: .prepone-extension-update

krfb:
  extends: .prepone-extension-update

krita:
  extends: .prepone-extension-update

kronometer:
  extends: .prepone-extension-update

kruler:
  extends: .prepone-extension-update

kshisen:
  extends: .prepone-extension-update

ksirk:
  extends: .prepone-extension-update

ksnakeduel:
  extends: .prepone-extension-update

kspaceduel:
  extends: .prepone-extension-update

ksquares:
  extends: .prepone-extension-update

ksystemlog:
  extends: .prepone-extension-update

kstars:
  extends: .prepone-extension-update

ksudoku:
  extends: .prepone-extension-update

kteatime:
  extends: .prepone-extension-update

ktimer:
  extends: .prepone-extension-update

ktorrent:
  extends: .prepone-extension-update

ktouch:
  extends: .prepone-extension-update

ktrip:
  extends: .prepone-extension-update

ktuberling:
  extends: .prepone-extension-update

kturtle:
  extends: .prepone-extension-update

kubrick:
  extends: .prepone-extension-update

kuiviewer:
  extends: .prepone-extension-update

kwave:
  extends: .prepone-extension-update

kweather:
  extends: .prepone-extension-update

kwordquiz:
  extends: .prepone-extension-update

kwrite:
  extends: .prepone-extension-update

labplot:
  extends: .prepone-extension-update

lokalize:
  extends: .prepone-extension-update

lskat:
  extends: .prepone-extension-update

marble:
  extends: .prepone-extension-update

massif-visualizer:
  extends: .prepone-extension-update

minuet:
  extends: .prepone-extension-update

neochat:
  extends: .prepone-extension-update

neon_ci_build.rb:
  extends: .prepone-extension-update

okteta:
  extends: .prepone-extension-update

okular:
  extends: .prepone-extension-update

palapeli:
  extends: .prepone-extension-update

parley:
  extends: .prepone-extension-update

partitionmanager:
  extends: .prepone-extension-update

peruse:
  extends: .prepone-extension-update

picmi:
  extends: .prepone-extension-update

qmlkonsole:
  extends: .prepone-extension-update

quassel:
  extends: .prepone-extension-update

rocs:
  extends: .prepone-extension-update

ruqola:
  extends: .prepone-extension-update

skanlite:
  extends: .prepone-extension-update

skanpage:
  extends: .prepone-extension-update

skrooge:
  extends: .prepone-extension-update

spectacle:
  extends: .prepone-extension-update

step:
  extends: .prepone-extension-update

subtitlecomposer:
  extends: .prepone-extension-update

sweeper:
  extends: .prepone-extension-update

symboleditor:
  extends: .prepone-extension-update

telly-skout:
  extends: .prepone-extension-update

tokodon:
  extends: .prepone-extension-update

umbrello:
  extends: .prepone-extension-update

yakuake:
  extends: .prepone-extension-update

zanshin:
  extends: .prepone-extension-update

kjournald:
  extends: .prepone-extension-update

ghostwriter:
  extends: .prepone-extension-update

kphotoalbum:
  extends: .prepone-extension-update
