---
name: dolphin
confinement: strict
grade: stable
base: core20
adopt-info: dolphin
apps:
    dolphin:
        extensions:
        - kde-neon
        common-id: org.kde.dolphin.desktop
        command: usr/bin/dolphin
        plugs:
        - home
        - network
        - network-bind
        - audio-playback
        - removable-media
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.dolphin
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    dolphin:
        plugin: cmake
        build-packages:
        - libkf5baloowidgets-dev
        - libphonon4qt5experimental-dev
        - pkg-config
        - kuserfeedback-dev
        - libphonon4qt5-dev
        - libkf5doctools-dev
        stage-packages:
        - dolphin-plugins
        - libglu1-mesa
        - freeglut3
        - libphonon4qt5experimental4
        - libkf5baloowidgets5
        - libkuserfeedbackcore1
        - libkuserfeedbackwidgets1
        source: http://download.kde.org/stable/release-service/21.12.3/src/dolphin-21.12.3.tar.xz
        cmake-parameters:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;/root/stage\\;/snap/kde-frameworks-5-qt-5-15-3-core20-sdk/current"
        parse-info:
        - usr/share/metainfo/org.kde.dolphin.appdata.xml
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/x86_64-linux-gnu/6.0.0"
            - "-usr/lib/aspell/*"
        prime:
        - "$exclusion"
version: 21.12.3
