---
name: artikulate
confinement: strict
grade: stable
base: core20
adopt-info: artikulate
version: 22.08.0
apps:
    artikulate:
        extensions:
        - kde-neon
        common-id: org.kde.artikulate.desktop
        command: usr/bin/artikulate
        environment:
            GST_PLUGIN_SCANNER: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gstreamer-1.0/"
        plugs:
        - home
        - network
        - network-bind
        - audio-playback
        - removable-media
        - audio-record
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    artikulate:
        parse-info:
        - usr/share/metainfo/org.kde.artikulate.appdata.xml
        plugin: cmake
        build-packages:
        - libkf5doctools-dev
        - libqt5gstreamer-dev
        - kirigami2-dev
        stage-packages:
        - libqt5gstreamer-1.0-0
        - libqt5gstreamerquick-1.0-0
        - libqt5gstreamerui-1.0-0
        - libqt5gstreamerutils-1.0-0
        - libslang2
        - qml-module-qtquick-shapes
        - qml-module-org-kde-kirigami2
        - qml-module-org-kde-kquickcontrolsaddons
        - qml-module-qtqml-models2
        source: http://download.kde.org/stable/release-service/22.08.0/src/artikulate-22.08.0.tar.xz
        cmake-parameters:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$SNAPCRAFT_STAGE\\;/snap/kde-frameworks-5-96-qt-5-15-5-core20-sdk/current"
        - "-DKDE_INSTALL_PLUGINDIR=/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/plugins/"
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/$SNAPCRAFT_ARCH_TRIPLET/6.0.0"
            - "-usr/lib/aspell/*"
        prime:
        - "$exclusion"
