---
name: kontact
confinement: devmode
grade: devel
base: core20
adopt-info: kontact
apps:
    kontact:
        extensions:
        - kde-neon
        common-id: org.kde.kontact.desktop
        command: kf5-launch-ext $SNAP/dbus-wrapper $SNAP/akonadi-wrapper $SNAP/usr/bin/kontact
        plugs:
        - home
        - audio-playback
        - removable-media
        - browser-support
    bash:
        command: kf5-launch-ext $SNAP/dbus-wrapper bash
        plugs:
        - home
        - x11
        - audio-playback
    akonadictl:
        command: kf5-launch-ext $SNAP/dbus-wrapper $SNAP/usr/bin/akonadictl
        plugs:
        - home
        - audio-playback
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
layout:
    "/usr/share/qt5":
        bind: "$SNAP/kf5/usr/share/qt5"
parts:
    runtime:
        source: runtime
        plugin: dump
    psmisc:
        plugin: nil
        stage-packages:
        - psmisc
    kontact:
        parse-info:
        - usr/share/metainfo/org.kde.kontact.appdata.xml
        plugin: cmake
        build-packages:
        - kross-dev
        - libassuan-dev
        - libboost-dev
        - libboost-graph-dev
        - libgpgme-dev
        - libgrantlee5-dev
        - libkf5akonadi-dev
        - libkf5akonadiserver-dev
        - libkf5eventviews-dev
        - libkf5grantleetheme-dev
        - libkf5kdelibs4support-dev
        - libkf5kdepimdbusinterfaces-dev
        - libkf5khtml-dev
        - libkf5kontactinterface-dev
        - libkf5libkdepim-dev
        - libkf5mailcommon-dev
        - libkf5messagecomposer-dev
        - libkf5mimetreeparser-dev
        - libkf5pimtextedit-dev
        - libkf5templateparser-dev
        stage-packages:
        - kross
        - libassuan0
        - libgpgme11
        - libgrantlee-templates5
        - libgrantlee-textdocument5
        - libkf5akonadicore5
        - libkf5akonadiagentbase5
        - libkf5akonadiwidgets5
        - libkf5akonadixml5
        - libkf5akonadiprivate5
        - libkf5eventviews5
        - libkf5grantleetheme5
        - libkf5kdelibs4support5
        - libkf5kontactinterface5
        - libkf5libkdepim5
        - libkf5mailcommon5
        - libkf5messagecomposer5
        - libkf5mimetreeparser5
        - libkf5pimtextedit5
        - libkf5templateparser5
        - libkf5grantleetheme-plugins
        - libqt5webchannel5
        - libqt5webkit5
        - kdepim-runtime
        - accountwizard
        - akregator
        - kaddressbook
        - kmail
        - knotes
        - korganizer
        - sasl2-bin
        - libsasl2-modules
        source: http://download.kde.org/stable/release-service/22.08.0/src/kontact-22.08.0.tar.xz
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/$SNAPCRAFT_ARCH_TRIPLET/6.0.0"
            - "-usr/lib/aspell/*"
        prime:
        - "$exclusion"
        - "-etc/xdg/autostart/org.kde.korgac.desktop"
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$SNAPCRAFT_STAGE\\;/snap/kde-frameworks-5-96-qt-5-15-5-core20-sdk/current"
version: 22.08.0
