#Bump build 3
---
name: blinken
confinement: strict
grade: stable
base: core22
adopt-info: blinken
version: 22.12.3
apps:
    blinken:
        extensions:
        - kde-neon
        common-id: org.kde.blinken.desktop
        desktop: usr/share/applications/org.kde.blinken.desktop
        command: usr/bin/blinken
        plugs:
        - audio-playback
        - unity7
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.blinken
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - jammy
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    blinken:
        plugin: cmake
        build-packages:
        - cmake
        - libkf5doctools-dev
        - libphonon4qt5-dev
        - libphonon4qt5experimental-dev
        build-snaps:
        - kf5-5-104-qt-5-15-8-core22-sdk
        source: http://download.kde.org/stable/release-service/22.12.3/src/blinken-22.12.3.tar.xz
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$CRAFT_STAGE\\;/snap/kf5-5-104-qt-5-15-8-core22-sdk/current"
        prime:
        - "-usr/lib/*/cmake/*"
        - "-usr/include/*"
        - "-usr/share/ECM/*"
        - "-usr/share/doc/*"
        - "-usr/share/man/*"
        - "-usr/share/icons/breeze-dark*"
        - "-usr/bin/X11"
        - "-usr/lib/gcc/$CRAFT_ARCH_TRIPLET/6.0.0"
        - "-usr/lib/aspell/*"
    cleanup:
        after:
        - blinken
        plugin: nil
        build-snaps:
        - kf5-5-104-qt-5-15-8-core22
        override-prime: |
            set -eux
            # for snap in "kf5-5-104-qt-5-15-8-core22"; do  # List all content-snaps you're using here
            #     cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$CRAFT_PRIME/{}" "$CRAFT_PRIME/usr/{}" \;
            # done
            find $CRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
            find $CRAFT_PRIME/usr/share -type d -empty -delete
