---
name: kalarm
confinement: strict
grade: stable
base: core20
adopt-info: kalarm
apps:
    kalarm:
        extensions:
        - kde-neon
        common-id: org.kde.kalarm.desktop
        command: usr/bin/kalarm
        plugs:
        - home
        - network
        - network-bind
        - audio-playback
        - removable-media
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.kalarm
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    kalarm:
        parse-info:
        - usr/share/metainfo/org.kde.kalarm.appdata.xml
        plugin: cmake
        build-packages:
        - kross-dev
        - libassuan-dev
        - libboost-dev
        - libboost-graph-dev
        - libkf5akonadi-dev
        - libkf5akonadicalendar-dev
        - libkf5akonadicontact-dev
        - libkf5akonadimime-dev
        - libkf5akonadiserver-dev
        - libkf5alarmcalendar-dev
        - libkf5calendarcore-dev
        - libkf5calendarutils-dev
        - libkf5contacteditor-dev
        - libkf5contacts-dev
        - libkf5dnssd-dev
        - libkf5holidays-dev
        - libkf5identitymanagement-dev
        - libkf5kdepimdbusinterfaces-dev
        - libkf5khtml-dev
        - libkf5libkdepim-dev
        - libkf5mailcommon-dev
        - libkf5mailtransport-dev
        - libkf5messagecomposer-dev
        - libkf5mime-dev
        - libkf5mimetreeparser-dev
        - libkf5pimcommon-dev
        - libkf5pimtextedit-dev
        - libkf5templateparser-dev
        - libkf5webengineviewer-dev
        - libphonon4qt5-dev
        - libphonon4qt5experimental-dev
        - pkg-config
        - xsltproc
        - zlib1g-dev
        stage-packages:
        - kross
        - libassuan
        - libboost
        - libboost-graph
        - libkf5akonadi
        - libkf5akonadicalendar
        - libkf5akonadicontact
        - libkf5akonadimime
        - libkf5akonadiserver
        - libkf5alarmcalendar
        - libkf5calendarcore
        - libkf5calendarutils
        - libkf5contacteditor
        - libkf5contacts
        - libkf5dnssd
        - libkf5holidays
        - libkf5identitymanagement
        - libkf5kdepimdbusinterfaces
        - libkf5khtml
        - libkf5libkdepim
        - libkf5mailcommon
        - libkf5mailtransport
        - libkf5messagecomposer
        - libkf5mime
        - libkf5mimetreeparser
        - libkf5pimcommon
        - libkf5pimtextedit
        - libkf5templateparser
        - libkf5webengineviewer
        - pkg-config
        - xsltproc
        - zlib1g
        source: http://download.kde.org/stable/release-service/22.04.0/src/kalarm-22.04.0.tar.xz
        cmake-parameters:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/root/stage\\;/snap/kde-frameworks-5-qt-5-15-3-core20-sdk/current"
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/x86_64-linux-gnu/6.0.0"
            - "-usr/lib/aspell/*"
        prime:
        - "$exclusion"
version: 22.04.0
