---
name: kalarm
confinement: strict
grade: stable
base: core20
adopt-info: kalarm
apps:
    kalarm:
        extensions:
        - kde-neon
        common-id: org.kde.kalarm.desktop
        command: usr/bin/kalarm
        environment:
            GST_PLUGIN_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gstreamer-1.0"
            GST_PLUGIN_SYSTEM_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gstreamer-1.0"
            GST_PLUGIN_SCANNER: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner"
        plugs:
        - home
        - network
        - network-bind
        - audio-playback
        - removable-media
layout:
    "/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib":
        symlink: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib"
    "/usr/share/alsa":
        symlink: "$SNAP/usr/share/alsa"
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.kalarm
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    kalarm:
        parse-info:
        - usr/share/metainfo/org.kde.kalarm.appdata.xml
        plugin: cmake
        build-packages:
        - kross-dev
        - libassuan-dev
        - libboost-dev
        - libboost-graph-dev
        - pkg-config
        - xsltproc
        - zlib1g-dev
        stage-packages:
        - libasound2
        - libasound2-data
        - libasound2-plugins
        - phonon4qt5
        - gstreamer1.0-alsa
        - gstreamer1.0-pulseaudio
        - gstreamer1.0-plugins-good
        - gstreamer1.0-plugins-bad
        - gstreamer1.0-plugins-ugly
        - phonon4qt5-backend-gstreamer
        - oxygen-sounds
        - kross
        - libassuan
        - libboost-graph
        - pkg-config
        - xsltproc
        - zlib1g
        source: http://download.kde.org/stable/release-service/22.08.1/src/kalarm-22.08.1.tar.xz
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=$SNAPCRAFT_STAGE\\;/snap/kde-frameworks-5-98-qt-5-15-6-core20-sdk/current"
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/$SNAPCRAFT_ARCH_TRIPLET/6.0.0"
            - "-usr/lib/aspell/*"
            - "-usr/share/lintain"
        prime:
        - "$exclusion"
    cleanup:
        after:
        - kalarm
        plugin: nil
        build-snaps:
        - kde-frameworks-5-98-qt-5-15-6-core20
        override-prime: |
            set -eux
            for snap in "kde-frameworks-5-98-qt-5-15-6-core20"; do  # List all content-snaps you're using here
                cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" "$SNAPCRAFT_PRIME/usr/{}" \;
            done
            find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
            find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
version: 22.08.1
