---
name: labplot
version: 2.9.0
confinement: strict
grade: stable
base: core20
adopt-info: labplot
apps:
    labplot:
        common-id: org.kde.labplot2.desktop
        command: usr/bin/labplot2
        extensions:
        - kde-neon
        plugs:
        - home
        - network
        - network-bind
        - removable-media
        - audio-playback
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.labplot
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    labplot:
        parse-info:
        - usr/share/metainfo/org.kde.labplot2.appdata.xml
        plugin: cmake
        build-packages:
        - libkf5xmlgui-data
        - libkf5xmlgui5
        - libcantorlibs-dev
        - libhdf5-dev
        - libgsl-dev
        - libfftw3-dev
        - bison
        - libkf5kdelibs4support-dev
        - libkf5syntaxhighlighting-dev
        - libqt5serialport5-dev
        - kuserfeedback-dev
        - libnetcdf-dev
        - libcfitsio-dev
        - libcerf-dev
        - liblz4-dev
        - extra-cmake-modules
        - libqt5svg5-dev
        - gettext
        - libpoppler-dev
        - libpoppler-qt5-dev
        stage-packages:
        - kio
        - libkuserfeedbackwidgets1
        - libgsl23
        - libfftw3-double3
        - bison
        - libkf5kdelibs4support5
        - libhdf5-103
        - libxcb-keysyms1
        - libxcb1
        - libasn1-8-heimdal
        - libbrotli1
        - libcantorlibs28
        - libcerf1
        - libcfitsio8
        - libcurl3-gnutls
        - libgs9
        - libgssapi3-heimdal
        - libhcrypto4-heimdal
        - libheimbase1-heimdal
        - libheimntlm0-heimdal
        - libhx509-5-heimdal
        - libidn11
        - libijs-0.35
        - libjbig0
        - libjbig2dec0
        - libkrb5-26-heimdal
        - liblcms2-2
        - libldap-2.4-2
        - libnetcdf15
        - libnghttp2-14
        - libnspr4
        - libnss3
        - libopenjp2-7
        - libpaper1
        - libpsl5
        - libroken18-heimdal
        - librtmp1
        - libsasl2-2
        - libspectre1
        - libssh-4
        - libtiff5
        - libwebp6
        - libwind0-heimdal
        source: https://download.kde.org/stable/labplot/2.9.0/labplot-2.9.0.tar.xz
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$SNAPCRAFT_STAGE\\;/snap/kde-frameworks-5-qt-5-15-core20-sdk/current"
