---
name: labplot
version: 2.8.2
confinement: strict
grade: stable
base: core20
adopt-info: labplot
apps:
    labplot:
        common-id: org.kde.labplot2.desktop
        command: kf5-launch labplot2
        plugs:
        - kde-frameworks-5-plug
        - home
        - x11
        - opengl
        - network
        - network-bind
        - audio-playback
        - desktop
        - desktop-legacy
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.labplot
        bus: session
plugs:
    kde-frameworks-5-plug:
        content: kde-frameworks-5-qt-5-15-core20-all
        interface: content
        default-provider: kde-frameworks-5-qt-5-15-core20
        target: kf5
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    patches:
        source: patch/
        plugin: dump
        prime:
        - "-*"
        stage:
        - std-isnan.diff
    labplot:
        parse-info:
        - usr/share/metainfo/org.kde.labplot2.appdata.xml
        build-snaps:
        - kde-frameworks-5-qt-5-15-core20-sdk/latest/candidate
        after:
        - kde-frameworks-5-env
        - patches
        plugin: cmake
        build-environment:
        -   CMAKE_BUILD_PARALLEL_LEVEL: '4'
        -   VERBOSE: '1'
        override-build: |-
            cd $SNAPCRAFT_PART_SRC
            patch -p1 < $SNAPCRAFT_STAGE/std-isnan.diff
            cp src/org.kde.labplot2.desktop .
            snapcraftctl build
        build-packages:
        - libkf5xmlgui-data
        - libkf5xmlgui5
        - libcantorlibs-dev
        - libhdf5-dev
        - libgsl-dev
        - libfftw3-dev
        - bison
        - libkf5kdelibs4support-dev
        - libkf5syntaxhighlighting-dev
        - libqt5serialport5-dev
        - kuserfeedback-dev
        - libnetcdf-dev
        - libcfitsio-dev
        - libcerf-dev
        - liblz4-dev
        - extra-cmake-modules
        - libqt5svg5-dev
        - gettext
        - libpoppler-dev
        - libpoppler-qt5-dev
        stage-packages:
        - libkuserfeedbackwidgets1
        - libgsl23
        - libfftw3-double3
        - bison
        - libkf5kdelibs4support5
        - libhdf5-103
        - libxcb-keysyms1
        - libxcb1
        - libasn1-8-heimdal
        - libbrotli1
        - libcantorlibs28
        - libcerf1
        - libcfitsio8
        - libcurl3-gnutls
        - libgs9
        - libgssapi3-heimdal
        - libhcrypto4-heimdal
        - libheimbase1-heimdal
        - libheimntlm0-heimdal
        - libhx509-5-heimdal
        - libidn11
        - libijs-0.35
        - libjbig0
        - libjbig2dec0
        - libkrb5-26-heimdal
        - liblcms2-2
        - libldap-2.4-2
        - libnetcdf15
        - libnghttp2-14
        - libnspr4
        - libnss3
        - libopenjp2-7
        - libpaper1
        - libpsl5
        - libroken18-heimdal
        - librtmp1
        - libsasl2-2
        - libspectre1
        - libssh-4
        - libtiff5
        - libwebp6
        - libwind0-heimdal
        source: https://download.kde.org/stable/labplot/2.8.2/labplot-2.8.2.tar.xz
        cmake-parameters:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;/root/stage\\;/snap/kde-frameworks-5-qt-5-15-core20-sdk/current"
    kde-frameworks-5-env:
        plugin: dump
        source: https://invent.kde.org/packaging/snap-kf5-launcher.git
