---
name: skanlite
confinement: strict
grade: stable
base: core20
adopt-info: skanlite
apps:
    skanlite:
        extensions:
        - kde-neon
        common-id: org.kde.skanlite.desktop
        command: usr/bin/skanlite
        plugs:
        - home
        - network
        - network-bind
        - audio-playback
        - removeable-media
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.skanlite
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    ksanecore:
        plugin: cmake
        build-packages:
        - libsane-dev
        stage-packages:
        - libsane
        source: http://download.kde.org/stable/release-service/22.08.2/src/ksanecore-22.08.2.tar.xz
        cmake-parameters:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=FALSE"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$SNAPCRAFT_STAGE\\;/snap/kde-frameworks-5-98-qt-5-15-6-core20-sdk/current"
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/$SNAPCRAFT_ARCH_TRIPLET/6.0.0"
            - "-usr/lib/aspell/*"
        prime:
        - "$exclusion"
    libksane:
        after:
        - ksanecore
        plugin: cmake
        build-packages:
        - libsane-dev
        stage-packages:
        - libsane
        source: http://download.kde.org/stable/release-service/22.08.2/src/libksane-22.08.2.tar.xz
        cmake-parameters:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=FALSE"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$SNAPCRAFT_STAGE\\;/snap/kde-frameworks-5-98-qt-5-15-6-core20-sdk/current"
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/$SNAPCRAFT_ARCH_TRIPLET/6.0.0"
            - "-usr/lib/aspell/*"
        prime:
        - "$exclusion"
    skanlite:
        parse-info:
        - usr/share/metainfo/org.kde.skanlite.appdata.xml
        after:
        - ksanecore
        - libksane
        plugin: cmake
        build-packages:
        - libpng-dev
        - libkf5doctools-dev
        build-environment:
            - LDFLAGS: "-L$SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET"
        source: http://download.kde.org/stable/release-service/22.08.2/src/skanlite-22.08.2.tar.xz
        cmake-parameters:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=FALSE"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$SNAPCRAFT_STAGE\\;/snap/kde-frameworks-5-98-qt-5-15-6-core20-sdk/current"
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/$SNAPCRAFT_ARCH_TRIPLET/6.0.0"
            - "-usr/lib/aspell/*"
        prime:
        - "$exclusion"
    cleanup:
        after:
        - ksanecore
        - libksane
        - skanlite
        plugin: nil
        build-snaps:
        - kde-frameworks-5-98-qt-5-15-6-core20
        override-prime: |
            set -eux
            for snap in "kde-frameworks-5-98-qt-5-15-6-core20"; do  # List all content-snaps you're using here
                cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" "$SNAPCRAFT_PRIME/usr/{}" \;
            done
            find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
            find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
version: 22.08.2
