---
name: skanlite
confinement: strict
grade: stable
base: core20
adopt-info: skanlite
apps:
    skanlite:
        extensions:
        - kde-neon
        common-id: org.kde.skanlite.desktop
        command: skanlite
        plugs:
        - home
        - network
        - network-bind
        - audio-playback
        - removeable-media
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.skanlite
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    libksane:
        plugin: cmake
        build-packages:
        - libsane-dev
        stage-packages:
        - libsane
        source: https://anongit.kde.org/libksane.git
        cmake-parameters:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
    skanlite:
        parse-info:
        - usr/share/metainfo/org.kde.skanlite.appdata.xml
        after:
        - libksane
        plugin: cmake
        build-packages:
        - libpng-dev
        source: https://download.kde.org/stable/skanlite/2.2/skanlite-2.2.0.tar.xz
        cmake-parameters:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/snap/kde-frameworks-5-qt-5-15-3-core20-sdk/current"
