---
name: bomber
grade: stable
base: core20
adopt-info: bomber
apps:
    bomber:
        extensions:
        - kde-neon
        common-id: org.kde.bomber.desktop
        desktop: usr/share/applications/org.kde.bomber.desktop
        command: usr/bin/bomber
        plugs:
        - home
        - network
        - network-bind
        - audio-playback
        - removable-media
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.bomber
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
layout:
    "/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib":
        bind: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib"
    "/usr/share/alsa":
        bind: "$SNAP/usr/share/alsa"
parts:
    bomber:
        plugin: cmake
        source: http://download.kde.org/stable/release-service/22.12.1/src/bomber-22.12.1.tar.xz
        build-packages:
        - libkf5doctools-dev
        stage-packages:
        - libasound2-data
        - libasound2-plugins
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$SNAPCRAFT_STAGE\\;/snap/kde-frameworks-5-99-qt-5-15-7-core20-sdk/current"
        parse-info:
        - usr/share/metainfo/org.kde.bomber.appdata.xml
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/$SNAPCRAFT_ARCH_TRIPLET/6.0.0"
            - "-usr/lib/aspell/*"
        prime:
        - "$exclusion"
        - "-etc/alsa/conf.d/99-pulse.conf"
version: 22.12.1
