---
name: konversation
version: 1.6.2
summary: IRC client
description: |-
    Konversation is an IRC client which gives you speedy access to Freenode network's channels, where you will find support for most distributions. Its defaults are such that it needs no configuration other than telling it the name of your distribution channel, to get started.

    Features:

    - Standard IRC features
    - SSL server support
    - Bookmarking support
    - Easy to use graphical user interface
    - Multiple servers and channels in one single window
    - DCC file transfer
    - Multiple identities for different servers
    - Text decorations and colors
    - OnScreen Display for notifications
    - Automatic UTF-8 detection
    - Per channel encoding support
    - Theme support for nick icons
    - Highly configurable
confinement: strict
grade: stable

apps:
    konversation:
        command: kf5-launch konversation
        plugs:
        - kde-frameworks-5-plug
        - home
        - x11
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio

slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.konversation
        bus: session

plugs:
    kde-frameworks-5-plug:
        content: kde-frameworks-5-all
        interface: content
        default-provider: kde-frameworks-5
        target: kf5

parts:
    kde-frameworks-5-dev:
        plugin: dump
        prime: ["-*"]
        source: kde-frameworks-5-dev_amd64.tar.xz
    kde-frameworks-5-env:
        plugin: dump
        prime: [kf5-launch, kf5]
        source: https://github.com/apachelogger/kf5-snap-env.git
    konversation:
        after: [kde-frameworks-5-dev]
        plugin: cmake
        build-packages:
        - kdoctools-dev
        - libphonon4qt5-dev
        - libphonon4qt5experimental-dev
        - libqca-qt5-2-dev
        - libpulse0
        prime:
        - "-usr/share/doc/*"
        - "-usr/share/man/*"
        source: git://anongit.kde.org/konversation
        configflags:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
