---
name: isoimagewriter
base: core20
adopt-info: isoimagewriter
grade: stable
confinement: strict
version: '0.9'
apps:
    isoimagewriter:
        extensions:
        - kde-neon
        command: usr/bin/isoimagewriter
        common-id: org.kde.isoimagewriter
        plugs:
        - home
        - audio-playback
        - network
        - raw-usb
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.isoimagewriter
        bus: session
parts:
    isoimagewriter:
        source: https://invent.kde.org/utilities/isoimagewriter.git
        plugin: cmake
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DBUILD_TESTING=OFF"
        - "-DENABLE_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DUSE_KAUTH=off"
        parse-info:
        - usr/share/metainfo/org.kde.isoimagewriter.appdata.xml
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/$SNAPCRAFT_ARCH_TRIPLET/6.0.0"
            - "-usr/lib/aspell/*"
            - "-usr/share/lintain"
        prime:
        - "$exclusion"
    cleanup:
        after:
        - isoimagewriter
        plugin: nil
        build-snaps:
        - kde-frameworks-5-98-qt-5-15-6-core20
        override-prime: |
            set -eux
            for snap in "kde-frameworks-5-98-qt-5-15-6-core20"; do  # List all content-snaps you're using here
                cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" "$SNAPCRAFT_PRIME/usr/{}" \;
            done
            find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
            find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
