---
name: isoimagewriter
base: core20
adopt-info: isoimagewriter
grade: stable
confinement: strict
version: '0.9'
apps:
    isoimagewriter:
        extensions:
        - kde-neon
        command: usr/bin/isoimagewriter
        common-id: org.kde.isoimagewriter
        plugs:
        - home
        - audio-playback
        - network
        - raw-usb
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.isoimagewriter
        bus: session
parts:
    isoimagewriter:
        source: https://invent.kde.org/utilities/isoimagewriter.git
        plugin: cmake
        cmake-parameters:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DUSE_KAUTH=off"
        parse-info:
        - usr/share/metainfo/org.kde.isoimagewriter.appdata.xml
