---
name: kdf
confinement: strict
grade: stable
base: core20
adopt-info: kdf
apps:
    kdf:
        extensions:
        - kde-neon
        common-id: org.kde.kdf
        command: usr/bin/kdf
        plugs:
        - home
        - network
        - network-bind
        - audio-playback
        - removable-media
        - mount-observe
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    kdf:
        parse-info:
        - usr/share/metainfo/org.kde.kdf.appdata.xml
        plugin: cmake
        build-packages:
        - libkf5doctools-dev
        - extra-cmake-modules
        stage-packages:
        - coreutils
        source: http://download.kde.org/stable/release-service/21.12.0/src/kdf-21.12.0.tar.xz
        cmake-parameters:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;/root/stage\\;/snap/kde-frameworks-5-qt-5-15-3-core20-sdk/current"
        - "-DKDE_INSTALL_PLUGINDIR=/usr/lib/x86_64-linux-gnu/qt5/plugins/"
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/x86_64-linux-gnu/6.0.0"
            - "-usr/lib/aspell/*"
        prime:
        - "$exclusion"
