---
name: digikam
base: core22
version: 7.10.0
adopt-info: digikam
grade: stable
confinement: strict
apps:
    digikam:
        command: usr/bin/digikam
        common-id: org.kde.digikam.desktop
        desktop: usr/share/applications/org.kde.digikam.desktop
        # extensions:
        # - kde-neon
        plugs:
        - desktop
        - desktop-legacy
        - opengl
        - wayland
        - x11
        - audio-playback
        - browser-support
        - camera
        - home
        - mount-observe
        - network
        - network-bind
        - removable-media
        - udisks2
        command-chain:
        - snap/command-chain/desktop-launch
assumes:
- snapd2.43
compression: lzo
plugs:
    desktop:
        mount-host-font-cache: false
    icon-themes:
        interface: content
        target: $SNAP/data-dir/icons
        default-provider: gtk-common-themes
    sound-themes:
        interface: content
        target: $SNAP/data-dir/sounds
        default-provider: gtk-common-themes
    kf5-5-104-qt-5-15-8-core22:
        content: kf5-5-104-qt-5-15-8-core22-all
        interface: content
        default-provider: kf5-5-104-qt-5-15-8-core22:kf5-5-104-qt-5-15-8-core22
        target: $SNAP/kf5
environment:
    SNAP_DESKTOP_RUNTIME: $SNAP/kf5
    DK_PLUGIN_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/plugins/digikam"
    PERL5LIB: "$SNAP/usr/share/perl5"
hooks:
    configure:
        plugs:
        - desktop
        command-chain:
        - snap/command-chain/hooks-configure-desktop
layout:
    /usr/share/marble:
        symlink: $SNAP/usr/share/marble
    /usr/share/qt5:
        symlink: $SNAP/kf5/usr/share/qt5
    /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
        symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
    /usr/share/alsa:
        symlink: $SNAP/usr/share/alsa
    /usr/share/X11:
        symlink: $SNAP/kf5/usr/share/X11
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.digikam
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - jammy
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    kde-neon:
        source: /snap/snapcraft/current/share/snapcraft/extensions/desktop/kde-neon
        source-type: local
        plugin: make
        make-parameters:
        - PLATFORM_PLUG=kf5-5-104-qt-5-15-8-core22
        build-snaps:
        - kf5-5-104-qt-5-15-8-core22-sdk
        build-environment: &id007
        - &id001
            PATH: /snap/kf5-5-104-qt-5-15-8-core22-sdk/current/usr/bin${PATH:+:$PATH}
        - &id002
            XDG_DATA_DIRS: $SNAPCRAFT_STAGE/usr/share:/snap/kf5-5-104-qt-5-15-8-core22-sdk/current/usr/share:/usr/share${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}
        - &id003
            LD_LIBRARY_PATH: /snap/kf5-5-104-qt-5-15-8-core22-sdk/current/lib/$CRAFT_ARCH_TRIPLET:/snap/kf5-5-104-qt-5-15-8-core22-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET:/snap/kf5-5-104-qt-5-15-8-core22-sdk/current/usr/lib:/snap/kf5-5-104-qt-5-15-8-core22-sdk/current/usr/lib/vala-current:/snap/kf5-5-104-qt-5-15-8-core22-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/pulseaudio${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
        - &id004
            PKG_CONFIG_PATH: /snap/kf5-5-104-qt-5-15-8-core22-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig:/snap/kf5-5-104-qt-5-15-8-core22-sdk/current/usr/lib/pkgconfig:/snap/kf5-5-104-qt-5-15-8-core22-sdk/current/usr/share/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
        - &id005
            ACLOCAL_PATH: /snap/kf5-5-104-qt-5-15-8-core22-sdk/current/usr/share/aclocal${ACLOCAL_PATH:+:$ACLOCAL_PATH}
        - &id006
            SNAPCRAFT_CMAKE_ARGS: -DCMAKE_FIND_ROOT_PATH=/snap/kf5-5-104-qt-5-15-8-core22-sdk/current${SNAPCRAFT_CMAKE_ARGS:+:$SNAPCRAFT_CMAKE_ARGS}
    opencv:
        source: https://github.com/opencv/opencv/archive/3.4.9.zip
        source-subdir: opencv-3.4.9
        plugin: cmake
        build-packages:
        - cmake
        - libglib2.0-dev
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/"
        prime:
        - "-include"
    marble:
        after:
        - kde-neon
        - opencv
        source: https://invent.kde.org/education/marble.git
        source-tag: v20.04.0
        source-type: git
        plugin: cmake
        build-packages:
        - cmake
        - docbook-xml
        - docbook-xsl
        build-environment:
        - *id001
        - *id002
        - *id003
        - *id004
        - *id005
        - *id006
        - PATH: /usr/lib/ccache:$PATH
        stage-packages:
        - libiw30
        - libshp2
        - libwlocate0
        cmake-parameters:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=FALSE"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DWITH_KF5=TRUE"
        - "-DWITH_DESIGNER_PLUGIN=OFF"
        - "-DBUILD_MARBLE_TESTS=OFF"
        - "-DBUILD_MARBLE_TOOLS=OFF"
        - "-DBUILD_MARBLE_EXAMPLES=OFF"
        - "-DBUILD_MARBLE_APPS=OFF"
        - "-DBUILD_WITH_DBUS=ON"
        - "-DBUILD_TESTING=OFF"
        - "-Wno-dev"
    lensfun:
        after:
        - kde-neon
        - opencv
        - marble
        source: https://github.com/lensfun/lensfun.git
        plugin: cmake
        build-packages:
        - cmake
        cmake-parameters:
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DBUILD_STATIC=OFF"
        - "-DBUILD_WITH_MSVC_STATIC_RUNTIME=OFF"
        - "-DBUILD_TESTS=OFF"
        - "-DBUILD_LENSTOOL=OFF"
        - "-DBUILD_DOC=OFF"
        - "-DINSTALL_PYTHON_MODULE=OFF"
        - "-DINSTALL_HELPER_SCRIPTS=OFF"
    qtav:
        after:
        - kde-neon
        - opencv
        - marble
        - lensfun
        source: https://github.com/wang-bin/QtAV.git
        plugin: cmake
        build-packages:
        - cmake
        - libavcodec-dev
        - libavdevice-dev
        - libavfilter-dev
        - libavformat-dev
        - libavresample-dev
        - libavutil-dev
        - libpulse-dev
        stage-packages:
        - libavcodec58
        - libavdevice58
        - libavfilter7
        - libavformat58
        - libavresample4
        - libavutil56
        - libswscale5
        build-environment:
        - *id007
        -   PATH: "/usr/lib/ccache:$PATH"
        cmake-parameters:
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DBUILD_TESTS=OFF"
        - "-DBUILD_EXAMPLES=OFF"
        - "-DBUILD_PLAYERS=OFF"
        - "-DBUILD_QT5OPENGL=ON"
        - "-DBUILD_QML=OFF"
        stage:
        - etc/
        - usr/
        - lib/
        - "-usr/lib/$CRAFT_ARCH_TRIPLET/libtiff.so.5.5.0"
        - "-usr/share/doc/libtiff5/changelog.Debian.gz"
    digikam:
        after:
        - kde-neon
        - qtav
        - marble
        - opencv
        - lensfun
        source: http://download.kde.org/stable/digikam/7.10.0/digiKam-7.10.0.tar.xz
        plugin: cmake
        stage-packages:
        - cmake
        - libexif12
        - libgphoto2-6
        - libgphoto2-port12
        - libheif1
        - libimage-exiftool-perl
        - libjpeg8
        - libjpeg-turbo8
        - liblensfun1
        - liblqr-1-0
        - libltdl7
        - libtbb2
        - libwlocate0
        - libshp2
        - libx265-179
        build-packages:
        - bison
        - ccache
        - doxygen
        - g++
        - libboost-graph-dev
        - libegl1-mesa-dev
        - libeigen3-dev
        - libexpat1-dev
        - libfl-dev
        - libglib2.0-dev
        - libheif-dev
        - libjpeg-dev
        - liblensfun-dev
        - libmagickcore-dev
        - libpng-dev
        - libsane-dev
        - libsqlite3-dev
        - libtiff-dev
        - libxslt1-dev
        - libphonon4qt5-dev
        - libphonon4qt5experimental-dev
        - libshp-dev
        - libwlocate-dev
        - libx265-dev
        build-environment:
        - *id007
        -   PATH: "/usr/lib/ccache:$PATH"
        cmake-parameters:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=FALSE"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON"
        - "-DBUILD_TESTING=OFF"
        - "-DDIGIKAMSC_CHECKOUT_PO=OFF"
        - "-DDIGIKAMSC_CHECKOUT_DOC=OFF"
        - "-DDIGIKAMSC_COMPILE_PO=OFF"
        - "-DDIGIKAMSC_COMPILE_DOC=ON"
        - "-DDIGIKAMSC_COMPILE_DIGIKAM=ON"
        - "-DENABLE_KFILEMETADATASUPPORT=OFF"
        - "-DENABLE_AKONADICONTACTSUPPORT=OFF"
        - "-DENABLE_MYSQLSUPPORT=OFF"
        - "-DENABLE_INTERNALMYSQL=OFF"
        - "-DENABLE_MEDIAPLAYER=ON"
        - "-DENABLE_LCMS2=ON"
        - "-DDIGIKAMSC_USE_PRIVATE_KDEGRAPHICS=OFF"
        - "-DENABLE_DBUS=ON"
        - "-DENABLE_APPSTYLES=ON"
        - "-DENABLE_QWEBENGINE=ON"
        - "-DOpenCV_DIR=$SNAPCRAFT_STAGE/usr/share/OpenCV"
        - "-DENABLE_FACESENGINE_DNN=ON"
        - "-DCMAKE_PREFIX_PATH=$SNAPCRAFT_STAGE/usr"
        - "-Wno-dev"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$SNAPCRAFT_STAGE\\;/snap/kde-frameworks-5-99-qt-5-15-7-core20-sdk/current"
        # parse-info:
        # - usr/share/metainfo/org.kde.digikam.appdata.xml
        override-build: |
            snapcraftctl build

            sed -i "${CRAFT_PART_INSTALL}/usr/share/applications/org.kde.digikam.desktop" -e 's|Icon=digikam$|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/digikam.svg|'

            cd "${SCRAFT_PART_INSTALL}/usr/share/icons/hicolor/scalable/apps"
            gzip -d -c digikam.svgz > digikam.svg
