---
name: kgoldrunner
confinement: strict
grade: stable
base: core20
adopt-info: kgoldrunner
apps:
    kgoldrunner:
        extensions:
        - kde-neon
        common-id: org.kde.kgoldrunner.desktop
        command: usr/bin/kgoldrunner
        plugs:
        - home
        - network
        - network-bind
        - audio-playback
        - removable-media
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.kgoldrunner
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
layout:
    "/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib":
        bind: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib"
    "/usr/share/alsa":
        bind: "$SNAP/usr/share/alsa"
parts:
    kgoldrunner:
        parse-info:
        - usr/share/metainfo/org.kde.kgoldrunner.appdata.xml
        plugin: cmake
        build-packages:
        - libkf5doctools-dev
        source: http://download.kde.org/stable/release-service/21.12.0/src/kgoldrunner-21.12.0.tar.xz
        stage-packages:
        - libasound2-data
        - libasound2-plugins
        cmake-parameters:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;/root/stage\\;/snap/kde-frameworks-5-qt-5-15-3-core20-sdk/current"
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/x86_64-linux-gnu/6.0.0"
            - "-usr/lib/aspell/*"
        prime:
        - "$exclusion"
        - "-etc/alsa/conf.d/99-pulse.conf"
