---
name: akregator
version: 22.04.1
summary: A KDE News Feed Reader
description: Akregator is a news feed reader for the KDE desktop. It enables you to
    follow news sites, blogs and other RSS/Atom-enabled websites without the need
    to manually check for updates using a web browser. Akregator is designed to be
    both easy to use and to be powerful enough to read hundreds of news sources conveniently.
    It comes with Konqueror integration for adding news feeds and with an internal
    browser for easy news reading.
adopt-info: akregator
confinement: strict
grade: stable
apps:
    akregator:
        command: kf5-launch akregator
        plugs:
        - kde-frameworks-5-plug
        - home
        - x11
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio
        - desktop
        - desktop-legacy
    common-id: org.kde.akregator.desktop
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.akregator
        bus: session
plugs:
    kde-frameworks-5-plug:
        content: kde-frameworks-5-all
        interface: content
        default-provider: kde-frameworks-5
        target: kf5
parts:
    akregator:
        after:
        - kde-frameworks-5-dev
        - kde-frameworks-5-env
        plugin: cmake
        build-packages:
        - kross-dev
        - libassuan-dev
        - libgpgme-dev
        - libgrantlee5-dev
        - libkf5akonadi-dev
        - libkf5akonadimime-dev
        - libkf5akonadiserver-dev
        - libkf5contacteditor-dev
        - libkf5dnssd-dev
        - libkf5doctools-dev
        - libkf5grantleetheme-dev
        - libkf5kdelibs4support-dev
        - libkf5khtml-dev
        - libkf5kontactinterface-dev
        - libkf5libkdepim-dev
        - libkf5libkleo-dev
        - libkf5messagecomposer-dev
        - libkf5messagecore-dev
        - libkf5messagelist-dev
        - libkf5messageviewer-dev
        - libkf5mimetreeparser-dev
        - libkf5pimcommon-dev
        - libkf5pimtextedit-dev
        - libkf5syndication-dev
        - libkf5templateparser-dev
        - libkf5webengineviewer-dev
        - libphonon4qt5-dev
        - libphonon4qt5experimental-dev
        - pkg-config
        - xsltproc
        - zlib1g-dev
        - libpulse0
        source: http://download.kde.org/stable/release-service/22.04.1/src/akregator-22.04.1.tar.xz
        configflags:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        parse-info:
        - usr/share/metainfo/org.kde.akregator.appdata.xml
