---
name: akregator
version: 23.04.2
base: core22
adopt-info: akregator
confinement: strict
grade: stable
apps:
    akregator:
        # extensions:
        # - kde-neon
        common-id: org.kde.akregator.desktop
        command: usr/bin/akregator
        plugs:
        - home
        - desktop
        - desktop-legacy
        - opengl
        - wayland
        - x11
        - audio-playback
        - unity7
        - network
        - network-bind
        command-chain:
        - snap/command-chain/desktop-launch
assumes:
- snapd2.43
compression: lzo
plugs:
    desktop:
        mount-host-font-cache: false
    icon-themes:
        interface: content
        target: $SNAP/data-dir/icons
        default-provider: gtk-common-themes
    sound-themes:
        interface: content
        target: $SNAP/data-dir/sounds
        default-provider: gtk-common-themes
    kf5-5-106-qt-5-15-9-core22:
        content: kf5-5-106-qt-5-15-9-core22-all
        interface: content
        default-provider: kf5-5-106-qt-5-15-9-core22
        target: $SNAP/kf5
environment:
    SNAP_DESKTOP_RUNTIME: $SNAP/kf5
    GST_PLUGIN_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0"
    GST_PLUGIN_SYSTEM_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0"
    GST_PLUGIN_SCANNER: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner"
hooks:
    configure:
        plugs:
        - desktop
        command-chain:
        - snap/command-chain/hooks-configure-desktop
layout:
    "/usr/lib/$CRAFT_ARCH_TRIPLET/alsa-lib":
        symlink: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/alsa-lib"
    "/usr/share/alsa":
        symlink: "$SNAP/usr/share/alsa"
    /usr/share/X11:
        symlink: $SNAP/kf5/usr/share/X11
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.akregator
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - jammy
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    kde-neon:
        source: /snap/snapcraft/current/share/snapcraft/extensions/desktop/kde-neon
        source-type: local
        plugin: make
        make-parameters:
        - PLATFORM_PLUG=kf5-5-106-qt-5-15-9-core22
        build-snaps:
        - kf5-5-106-qt-5-15-9-core22-sdk
        build-environment:
        - &id001
            PATH: /snap/kf5-5-106-qt-5-15-9-core22-sdk/current/usr/bin${PATH:+:$PATH}
        - &id002
            XDG_DATA_DIRS: $CRAFT_STAGE/usr/share:/snap/kf5-5-106-qt-5-15-9-core22-sdk/current/usr/share:/usr/share${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}
        - &id003
            XDG_CONFIG_HOME: $CRAFT_STAGE/etc/xdg:/snap/kf5-5-106-qt-5-15-9-core22-sdk/current/etc/xdg:/etc/xdg${XDG_CONFIG_HOME:+:$XDG_CONFIG_HOME}
        - &id004
            CRAFT_CMAKE_ARGS: -DCMAKE_FIND_ROOT_PATH=/snap/kf5-5-106-qt-5-15-9-core22-sdk/current${CRAFT_CMAKE_ARGS:+:$CRAFT_CMAKE_ARGS}
    grantleetheme:
        after:
        - kde-neon
        plugin: cmake
        build-packages:
        - libgrantlee5-dev
        source: http://download.kde.org/stable/release-service/23.04.2/src/grantleetheme-23.04.2.tar.xz
        cmake-parameters:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=FALSE"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$CRAFT_STAGE\\;/snap/kf5-5-106-qt-5-15-9-core22-sdk/current"
        build-environment: &id005
        - *id001
        - *id002
        - *id003
        - *id004
        prime:
        - "-usr/lib/*/cmake/*"
        - "-usr/include/*"
        - "-usr/share/ECM/*"
        - "-usr/share/doc/*"
        - "-usr/share/man/*"
        - "-usr/share/icons/breeze-dark*"
        - "-usr/bin/X11"
        - "-usr/lib/gcc/$CRAFT_ARCH_TRIPLET/6.0.0"
        - "-usr/lib/aspell/*"
        - "-etc/alsa/conf.d/99-pulse.conf"
    kontactinterface:
        after:
        - kde-neon
        - grantleetheme
        plugin: cmake
        source: http://download.kde.org/stable/release-service/23.04.2/src/kontactinterface-23.04.2.tar.xz
        cmake-parameters:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=FALSE"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$CRAFT_STAGE\\;/snap/kf5-5-106-qt-5-15-9-core22-sdk/current"
        build-environment: *id005
        prime:
        - "-usr/lib/*/cmake/*"
        - "-usr/include/*"
        - "-usr/share/ECM/*"
        - "-usr/share/doc/*"
        - "-usr/share/man/*"
        - "-usr/share/icons/breeze-dark*"
        - "-usr/bin/X11"
        - "-usr/lib/gcc/$CRAFT_ARCH_TRIPLET/6.0.0"
        - "-usr/lib/aspell/*"
        - "-etc/alsa/conf.d/99-pulse.conf"
    libkdepim:
        after:
        - kde-neon
        - grantleetheme
        - kontactinterface
        plugin: cmake
        source: http://download.kde.org/stable/release-service/23.04.2/src/libkdepim-23.04.2.tar.xz
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$CRAFT_STAGE\\;/snap/kf5-5-106-qt-5-15-9-core22-sdk/current"
        build-environment: *id005
        prime:
        - "-usr/lib/*/cmake/*"
        - "-usr/include/*"
        - "-usr/share/ECM/*"
        - "-usr/share/doc/*"
        - "-usr/share/man/*"
        - "-usr/share/icons/breeze-dark*"
        - "-usr/bin/X11"
        - "-usr/lib/gcc/$CRAFT_ARCH_TRIPLET/6.0.0"
        - "-usr/lib/aspell/*"
        - "-etc/alsa/conf.d/99-pulse.conf"
    kmime:
        after:
        - kde-neon
        - grantleetheme
        - kontactinterface
        - libkdepim
        plugin: cmake
        build-packages:
        - cmake
        source: http://download.kde.org/stable/release-service/23.04.2/src/kmime-23.04.2.tar.xz
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$CRAFT_STAGE\\;/snap/kf5-5-106-qt-5-15-9-core22-sdk/current"
        build-environment: *id005
        prime:
        - "-usr/lib/*/cmake/*"
        - "-usr/include/*"
        - "-usr/share/ECM/*"
        - "-usr/share/doc/*"
        - "-usr/share/man/*"
        - "-usr/share/icons/breeze-dark*"
        - "-usr/bin/X11"
        - "-usr/lib/gcc/$CRAFT_ARCH_TRIPLET/6.0.0"
        - "-usr/lib/aspell/*"
        - "-etc/alsa/conf.d/99-pulse.conf"
    xz:
        after:
        - kde-neon
        plugin: cmake
        build-packages:
        - cmake
        source: https://github.com/tukaani-project/xz/releases/download/v5.2.10/xz-5.2.10.tar.xz
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_PREFIX_PATH=$CRAFT_STAGE\\;/snap/kf5-5-106-qt-5-15-9-core22-sdk/current"
        - "-DCMAKE_FIND_ROOT_PATH=$CRAFT_STAGE\\;/snap/kf5-5-106-qt-5-15-9-core22-sdk/current"
        build-environment: *id005
        prime:
        - "-usr/lib/*/cmake/*"
        - "-usr/include/*"
        - "-usr/share/ECM/*"
        - "-usr/share/doc/*"
        - "-usr/share/man/*"
        - "-usr/share/icons/breeze-dark*"
        - "-usr/bin/X11"
        - "-usr/lib/gcc/$CRAFT_ARCH_TRIPLET/6.0.0"
        - "-usr/lib/aspell/*"
        - "-etc/alsa/conf.d/99-pulse.conf"
    akonadi:
        after:
        - kde-neon
        - grantleetheme
        - kontactinterface
        - libkdepim
        - kmime
        - xz
        plugin: cmake
        build-packages:
        - cmake
        - libaccounts-qt5-dev
        - libsqlite3-dev
        - libkaccounts-dev
        - liblzma-dev
        stage-packages:
        - libaccounts-qt5-1
        - libsqlite3-0
        - sqlite3
        - libkaccounts2
        - kaccounts-providers
        - qml-module-org-kde-kaccounts
        - kaccounts-integration
        - liblzma5
        source: http://download.kde.org/stable/release-service/23.04.2/src/akonadi-23.04.2.tar.xz
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_PREFIX_PATH=$CRAFT_STAGE\\;/snap/kf5-5-106-qt-5-15-9-core22-sdk/current"
        - "-DCMAKE_FIND_ROOT_PATH=$CRAFT_STAGE\\;/snap/kf5-5-106-qt-5-15-9-core22-sdk/current"
        build-environment: *id005
        prime:
        - "-usr/lib/*/cmake/*"
        - "-usr/include/*"
        - "-usr/share/ECM/*"
        - "-usr/share/doc/*"
        - "-usr/share/man/*"
        - "-usr/share/icons/breeze-dark*"
        - "-usr/bin/X11"
        - "-usr/lib/gcc/$CRAFT_ARCH_TRIPLET/6.0.0"
        - "-usr/lib/aspell/*"
        - "-etc/alsa/conf.d/99-pulse.conf"
    messagelib:
        after:
        - kde-neon
        - grantleetheme
        - kontactinterface
        - libkdepim
        - kmime
        - akonadi
        plugin: cmake
        build-packages:
        - cmake
        - libgpgmepp-dev
        - libkf5akonadi-dev
        stage-packages:
        - libgpgmepp6
        source: http://download.kde.org/stable/release-service/23.04.2/src/messagelib-23.04.2.tar.xz
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$CRAFT_STAGE\\;/snap/kf5-5-106-qt-5-15-9-core22-sdk/current"
        build-environment: *id005
        prime:
        - "-usr/lib/*/cmake/*"
        - "-usr/include/*"
        - "-usr/share/ECM/*"
        - "-usr/share/doc/*"
        - "-usr/share/man/*"
        - "-usr/share/icons/breeze-dark*"
        - "-usr/bin/X11"
        - "-usr/lib/gcc/$CRAFT_ARCH_TRIPLET/6.0.0"
        - "-usr/lib/aspell/*"
        - "-etc/alsa/conf.d/99-pulse.conf"
    akregator:
        after:
        - kde-neon
        - grantleetheme
        - kontactinterface
        - libkdepim
        - messagelib
        - akonadi
        parse-info:
        - usr/share/metainfo/org.kde.akregator.appdata.xml
        plugin: cmake
        build-packages:
        - libassuan-dev
        - libgpgme-dev
        - libgrantlee5-dev
        - libphonon4qt5-dev
        - libphonon4qt5experimental-dev
        - libkf5syndication-dev
        - pkg-config
        - xsltproc
        - zlib1g-dev
        - libpulse0
        - libkf5akonadi-dev
        - libkf5akonadi-dev-bin
        - libgpgmepp-dev
        stage-packages:
        - libkf5akonadicore5
        - libkf5akonadiagentbase5
        - libkf5akonadiwidgets5
        - libkf5akonadixml5
        - libqgpgme7
        source: http://download.kde.org/stable/release-service/23.04.2/src/akregator-23.04.2.tar.xz
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$CRAFT_STAGE\\;/snap/kf5-5-106-qt-5-15-9-core22-sdk/current"
        build-environment: *id005
        prime:
        - "-usr/lib/*/cmake/*"
        - "-usr/include/*"
        - "-usr/share/ECM/*"
        - "-usr/share/doc/*"
        - "-usr/share/man/*"
        - "-usr/share/icons/breeze-dark*"
        - "-usr/bin/X11"
        - "-usr/lib/gcc/$CRAFT_ARCH_TRIPLET/6.0.0"
        - "-usr/lib/aspell/*"
        - "-etc/alsa/conf.d/99-pulse.conf"
    cleanup:
        after:
        - syndication
        - grantleetheme
        - kontactinterface
        - libkdepim
        - akonadi
        - akregator
        plugin: nil
        override-prime: |
            set -eux
            #unused libs from linters
