---
name: kdenlive
confinement: strict
grade: stable
base: core20
adopt-info: kdenlive
compression: lzo
apps:
    kdenlive:
        extensions:
        - kde-neon
        common-id: org.kde.kdenlive.desktop
        command: usr/bin/kdenlive
        command-chain:
        - kdenlive-launch
        plugs:
        - home
        - network
        - network-bind
        - audio-playback
        - audio-record
        - removable-media
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.kdenlive
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    kdenlive:
        parse-info:
        - usr/share/metainfo/org.kde.kdenlive.appdata.xml
        plugin: cmake
        build-packages:
        - libqt5networkauth5-dev
        - libkf5doctools-dev
        - libkf5purpose-dev
        - libmlt++-dev
        - librttr-dev
        - libmlt-dev
        - libv4l-dev
        stage-packages:
        - libpsm-infinipath1
        - libqt5multimedia5
        - libqt5concurrent5
        - libqt5quickwidgets5
        - libqt5networkauth5
        - ffmpeg
        - frei0r-plugins
        - librttr-core0.9.6
        - libkf5purpose-bin
        - melt
        - dvdauthor
        - dvgrab
        - genisoimage
        - recordmydesktop
        - swh-plugins
        - libslang2
        - libmagic1
        - libgpm2
        - kio-extras
        source: http://download.kde.org/stable/release-service/21.08.0/src/kdenlive-21.08.0.tar.xz
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;/root/stage\\;/snap/kde-frameworks-5-qt-5-15-3-core20-sdk/current"
        override-build: |
            snapcraftctl build

            sed -i "${SNAPCRAFT_PART_INSTALL}/usr/share/applications/org.kde.kdenlive.desktop" -e 's|Icon=kdenlive$|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/kdenlive.svg|'

            cd "${SNAPCRAFT_PART_INSTALL}/usr/share/icons/hicolor/scalable/apps"
            gzip -d -c kdenlive.svgz > kdenlive.svg
    kdenlive-launch:
        source: kdenlive-launch/
        plugin: dump
        prime:
        - kdenlive-launch
