---
name: lokalize
confinement: strict
grade: stable
base: core20
adopt-info: lokalize
apps:
    lokalize:
        extensions:
        - kde-neon
        common-id: org.kde.lokalize.desktop
        command: usr/bin/lokalize
        plugs:
        - home
        - network
        - network-bind
        - audio-playback
        - removable-media
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.lokalize
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    lokalize:
        plugin: cmake
        build-packages:
        - kross-dev
        - libhunspell-dev
        - libkf5doctools-dev
        parse-info:
        - usr/share/metainfo/org.kde.lokalize.appdata.xml
        source: http://download.kde.org/stable/release-service/22.08.0/src/lokalize-22.08.0.tar.xz
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;/root/stage\\;/snap/kde-frameworks-5-96-qt-5-15-5-core20-sdk/current"
version: 22.08.0
