---
name: cervisia
confinement: strict
grade: stable
base: core20
adopt-info: cervisia
apps:
    cervisia:
        after: cvsservice5
        extensions:
        - kde-neon
        desktop: usr/share/applications/org.kde.cervisia.desktop
        command: usr/bin/cervisia
        plugs:
        - home
        - network
        - network-bind
        - audio-playback
        - removable-media
    cvsservice5:
        before: cervisia
        extensions:
        - kde-neon
        desktop: usr/share/applications/org.kde.cvsservice5.desktop
        command: usr/bin/cvsservice5
        daemon: simple
        plugs:
        - network
        - network-bind
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.cervisia5.repository
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    cervisia:
        parse-info:
        - usr/share/metainfo/org.kde.cervisia.appdata.xml
        plugin: cmake
        build-packages:
        - libkf5doctools-dev
        stage-packages:
        - kinit
        - libkf5service5
        - kded5
        source: http://download.kde.org/stable/release-service/22.12.2/src/cervisia-22.12.2.tar.xz
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$SNAPCRAFT_STAGE\\;/snap/kde-frameworks-5-99-qt-5-15-7-core20-sdk/current"
        - "-DKDE_INSTALL_PLUGINDIR=/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/plugins/"
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/$SNAPCRAFT_ARCH_TRIPLET/6.0.0"
            - "-usr/lib/aspell/*"
            - "-usr/share/lintain"
        prime:
        - "$exclusion"
    cleanup:
        after:
        - cervisia
        plugin: nil
        build-snaps:
        - kde-frameworks-5-99-qt-5-15-7-core20
        override-prime: |
            set -eux
            for snap in "kde-frameworks-5-99-qt-5-15-7-core20"; do  # List all content-snaps you're using here
                cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" "$SNAPCRAFT_PRIME/usr/{}" \;
            done
            find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
            find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
version: 22.12.2
