---
name: neochat
base: core20
adopt-info: neochat
grade: stable
confinement: strict
apps:
    neochat:
        extensions:
        - kde-neon
        command: usr/bin/neochat
        common-id: org.kde.neochat
        plugs:
        - home
        - audio-playback
        - network
        - network-manager-observe
        - password-manager-service
        environment:
            QML2_IMPORT_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qml"
            QT_QPA_PLATFORMTHEME: flatpak
            QT_QPA_FLATPAK_PLATFORMTHEME: kde
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.neochat
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    qtkeychain:
        source: https://github.com/frankosterfeld/qtkeychain.git
        source-tag: v0.13.2
        source-depth: 0
        plugin: cmake
        build-packages:
        - libsecret-1-dev
        stage-packages:
        - libsecret-1-0
        cmake-parameters:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=FALSE"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$SNAPCRAFT_STAGE\\;/snap/kde-frameworks-5-99-qt-5-15-7-core20-sdk/current"
        - "-DBUILD_TRANSLATIONS=NO"
    libmatrixclient:
        source: https://github.com/quotient-im/libQuotient.git
        source-tag: 0.6.11
        source-depth: 0
        plugin: cmake
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$SNAPCRAFT_STAGE\\;/snap/kde-frameworks-5-99-qt-5-15-7-core20-sdk/current"
    neochat:
        after:
        - qtkeychain
        - libmatrixclient
        source: http://download.kde.org/stable/plasma-mobile/22.11/neochat-22.11.tar.xz
        plugin: cmake
        cmake-parameters:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=FALSE"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$SNAPCRAFT_STAGE\\;/snap/kde-frameworks-5-99-qt-5-15-7-core20-sdk/current"
        stage-packages:
        - libcmark0.29.0
        - qml-module-org-kde-kquickimageeditor
        - qml-module-org-kde-qqc2desktopstyle
        build-packages:
        - gcc-10
        - g++-10
        - kirigami2-dev
        - libcmark-dev
        - kquickimageeditor-dev
        - libkf5qqc2desktopstyle-dev
        - qcoro-qt5-dev
        build-environment:
        -   CC: gcc-10
        -   CXX: g++-10
        parse-info:
        - usr/share/metainfo/org.kde.neochat.appdata.xml
    cleanup:
        after:
        - neochat
        plugin: nil
        build-snaps:
        - kde-frameworks-5-99-qt-5-15-7-core20
        override-prime: |
            set -eux
            for snap in "kde-frameworks-5-99-qt-5-15-7-core20"; do  # List all content-snaps you're using here
                cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" "$SNAPCRAFT_PRIME/usr/{}" \;
            done
            for CRUFT in bug lintian man; do
                rm -rf $SNAPCRAFT_PRIME/usr/share/$CRUFT
            done
            find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
            find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
version: '22.11'
