---
name: neochat
base: core20
adopt-info: neochat
grade: stable
confinement: strict
apps:
    neochat:
        extensions:
        - kde-neon
        command: usr/bin/neochat
        common-id: org.kde.neochat
        plugs:
        - home
        - audio-playback
        - network
        - network-manager-observe
        - password-manager-service
        environment:
            QML2_IMPORT_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qml"
            QT_QPA_PLATFORMTHEME: flatpak
            QT_QPA_FLATPAK_PLATFORMTHEME: kde
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.neochat
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    qtkeychain:
        source: https://github.com/frankosterfeld/qtkeychain.git
        source-tag: v0.13.2
        source-depth: 0
        plugin: cmake
        build-packages:
        - libsecret-1-dev
        stage-packages:
        - libsecret-1-0
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DBUILD_TRANSLATIONS=NO"
    libmatrixclient:
        source: https://github.com/quotient-im/libQuotient.git
        source-tag: 0.6.11
        source-depth: 0
        plugin: cmake
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DBUILD_TESTING=OFF"
    neochat:
        after:
        - qtkeychain
        - libmatrixclient
        source: http://download.kde.org/stable/plasma-mobile/22.06/neochat-22.06.tar.xz
        plugin: cmake
        cmake-parameters:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        stage-packages:
        - libcmark0.29.0
        build-packages:
        - libcmark-dev
        - kquickimageeditor-dev
        - libkf5qqc2desktopstyle-dev
        parse-info:
        - usr/share/metainfo/org.kde.neochat.appdata.xml
version: '22.06'
