---
name: konsole
confinement: classic
grade: stable
base: core22
adopt-info: konsole
version: 22.12.3
apps:
    konsole:
        # extensions:
        # - kde-neon
        command: usr/bin/konsole
        common-id: org.kde.konsole.desktop
assumes:
- snapd2.43
compression: lzo
environment:
    XDG_DATA_DIRS: "$XDG_DATA_DIRS:$SNAP/usr/share"
    XDG_CONFIG_DIRS: "$XDG_CONFIG_DIRS:$SNAP/etc/xdg"
layout:
    /usr/share/X11:
        symlink: $SNAP/kf5/usr/share/X11
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - jammy
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    konsole:
        parse-info:
        - usr/share/metainfo/org.kde.konsole.appdata.xml
        plugin: cmake
        build-packages:
        - cmake
        - extra-cmake-modules
        - qtbase5-dev
        stage-packages:
        - libqt5core5a
        source: http://download.kde.org/stable/release-service/22.12.3/src/konsole-22.12.3.tar.xz
        cmake-parameters:
        - -DKDE_INSTALL_USE_QT_SYS_PATHS=FALSE
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        prime:
        - "-usr/lib/*/cmake/*"
        - "-usr/include/*"
        - "-usr/share/ECM/*"
        - "-usr/share/doc/*"
        - "-usr/share/man/*"
        - "-usr/share/icons/breeze-dark*"
        - "-usr/bin/X11"
        - "-usr/lib/gcc/$CRAFT_ARCH_TRIPLET/6.0.0"
        - "-usr/lib/aspell/*"

