# trigger rebuild
---
name: konsole
confinement: classic
grade: stable
base: core22
adopt-info: konsole
version: 23.04.0
apps:
    konsole:
        # extensions:
        # - kde-neon
        command: usr/bin/konsole
        common-id: org.kde.konsole.desktop
assumes:
- snapd2.43
compression: lzo
environment:
    XDG_DATA_DIRS: "$XDG_DATA_DIRS:$SNAP/usr/share"
    XDG_CONFIG_DIRS: "$XDG_CONFIG_DIRS:$SNAP/etc/xdg"
layout:
    /usr/share/X11:
        symlink: $SNAP/kf5/usr/share/X11
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - jammy
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    konsole:
        parse-info:
        - usr/share/metainfo/org.kde.konsole.appdata.xml
        plugin: cmake
        build-packages:
        - cmake
        - extra-cmake-modules
        - qtbase5-dev
        - libicu-dev
        - libkf5bookmarks-dev
        - libkf5config-dev
        - libkf5coreaddons-dev
        - libkf5crash-dev
        - libkf5doctools-dev
        - libkf5globalaccel-dev
        - libkf5guiaddons-dev
        - libkf5dbusaddons-dev
        - libkf5i18n-dev
        - libkf5iconthemes-dev
        - libkf5kio-dev
        - libkf5newstuff-dev
        - libkf5notifications-dev
        - libkf5notifyconfig-dev
        - libkf5parts-dev
        - libkf5pty-dev
        - libkf5service-dev
        - libkf5textwidgets-dev
        - libkf5widgetsaddons-dev
        - libkf5windowsystem-dev
        - libkf5xmlgui-dev
        - qtmultimedia5-dev
        - gettext
        stage-packages:
        - libqt5core5a
        - libkf5bookmarks5
        - libkf5configcore5
        - libkf5configwidgets5
        - libkf5coreaddons5
        - libkf5crash5
        - libkf5globalaccel5
        - libkf5guiaddons5
        - libkf5dbusaddons5
        - libkf5i18n5
        - libkf5iconthemes5
        - libkf5kiocore5
        - kio
        - libkf5newstuffcore5
        - libkf5notifications5
        - libkf5notifyconfig5
        - libkf5parts5
        - libkf5pty5
        - libkf5service5
        - libkf5textwidgets5
        - libkf5widgetsaddons5
        - libkf5windowsystem5
        - libkf5xmlgui5
        - libqt5multimedia5
        - libicu70
        - gettext
        - breeze-icon-theme
        source: http://download.kde.org/stable/release-service/23.04.0/src/konsole-23.04.0.tar.xz
        cmake-parameters:
        - -DKDE_INSTALL_USE_QT_SYS_PATHS=FALSE
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        prime:
        - "-usr/lib/*/cmake/*"
        - "-usr/include/*"
        - "-usr/share/ECM/*"
        - "-usr/share/doc/*"
        - "-usr/share/man/*"
        - "-usr/share/icons/breeze-dark*"
        - "-usr/bin/X11"
        - "-usr/lib/gcc/$CRAFT_ARCH_TRIPLET/6.0.0"
        - "-usr/lib/aspell/*"

