---
name: kommit
confinement: strict
grade: stable
base: core20
adopt-info: kommit
version: 23.3.25
apps:
    kommit:
        extensions:
        - kde-neon
        common-id: org.kde.kommit.desktop
        command: usr/bin/kommit
        plugs:
        - home
        - network
        - network-bind
        - removable-media
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.kommit
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    kommit:
        parse-info:
        - usr/share/metainfo/org.kde.komit.appdata.xml
        plugin: cmake
        build-packages:
        - libkf5doctools-dev
        - extra-cmake-modules
        - libkf5i18n-dev
        - libkf5textwidgets-dev
        - libkf5texteditor-dev
        - libkf5coreaddons-dev
        - libkf5syntaxhighlighting-dev
        - libkf5crash-dev
        - libkf5kio-dev
        stage-packages:
        - libkf5kiofilewidgets5
        - libkf5kiocore5
        - libkf5kiowidgets5
        - libkf5syntaxhighlighting5
        - libkf5texteditor5
        - libqt5concurrent5
        source: https://invent.kde.org/sdk/kommit/-/archive/master/kommit-master.tar.gz
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$SNAPCRAFT_STAGE\\;/snap/kde-frameworks-5-96-qt-5-15-5-core20-sdk/current"
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/$SNAPCRAFT_ARCH_TRIPLET/6.0.0"
            - "-usr/lib/aspell/*"
        prime:
        - "$exclusion"
