---
name: kcolorchooser
confinement: strict
grade: stable
base: core20
adopt-info: kcolorchooser
apps:
    kcolorchooser:
        extensions:
        - kde-neon
        common-id: org.kde.kcolorchooser.desktop
        command: usr/bin/kcolorchooser
        plugs:
        - home
        - network
        - network-bind
        - audio-playback
        - removable-media
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.kcolorchooser
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    kcolorchooser:
        parse-info:
        - usr/share/metainfo/org.kde.kcolorchooser.appdata.xml
        plugin: cmake
        source: http://download.kde.org/stable/release-service/22.04.3/src/kcolorchooser-22.04.3.tar.xz
        cmake-parameters:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;/root/stage\\;/snap/kde-frameworks-5-96-qt-5-15-5-core20-sdk/current"
