---
name: kdevelop
confinement: classic
version: 22.04.0
grade: stable
base: core20
adopt-info: kdevelop
apps:
    kdevelop:
        command: usr/bin/kdevelop
        environment:
            QT_PLUGIN_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/plugins:$SNAPCRAFT_ARCH_TRIPLET/usr/lib/x86_64-linux-gnu"
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    kdevelop:
        plugin: cmake
        build-packages:
        - extra-cmake-modules
        - libboost-dev
        - libastyle-dev
        - libkf5doctools-dev
        - libclang-11-dev
        - libkomparediff2-dev
        - libsvn-dev
        - okteta-dev
        - libkf5purpose-dev
        - libkf5sysguard-dev
        - kdevelop-pg-qt
        - libgrantlee5-dev
        - libkf5config-dev
        - libkf5crash-dev
        - libkf5declarative-dev
        - libkf5i18n-dev
        - libkf5iconthemes-dev
        - libkf5itemmodels-dev
        - libkf5itemviews-dev
        - libkf5jobwidgets-dev
        - libkf5kcmutils-dev
        - libkf5kio-dev
        - libkf5newstuff-dev
        - libkf5notifyconfig-dev
        - libkf5parts-dev
        - libkf5plasma-dev
        - libkf5runner-dev
        - libkf5service-dev
        - libkf5syntaxhighlighting-dev
        - libkf5texteditor-dev
        - libkf5threadweaver-dev
        - libkf5windowsystem-dev
        - libkf5xmlgui-dev
        - libqt5webkit5-dev
        - gettext
        stage-packages:
        - konsole-kpart
        - libgrantlee-templates5
        - libgrantlee-textdocument5
        - libapr1
        - libaprutil1
        - libastyle3
        - libclang1-11
        - libclang-11-dev
        - libkasten4controllers0
        - libkasten4core0
        - libkasten4gui0
        - libkasten4okteta2controllers0
        - libkasten4okteta2core0
        - libkasten4okteta2gui0
        - libkomparediff2-5
        - libokteta3core0
        - libokteta3gui0
        - libqca-qt5-2
        - libserf-1-1
        - libsvn1
        - libutf8proc2
        - llvm-11-dev
        - libkf5purpose5
        - libksysguardformatter1
        - libprocesscore9
        - libprocessui9
        - libbrotli1
        - libeditorconfig0
        - libglu1-mesa
        - libgstreamer-plugins-base1.0-0
        - libgstreamer1.0-0
        - libhyphen0
        - libkf5itemmodels5
        - libkf5plasma5
        - libkf5runner5
        - libkf5syntaxhighlighting5
        - libkf5texteditor5
        - libkf5threadweaver5
        - liborc-0.4-0
        - libqt5sensors5
        - libqt5sql5
        - libqt5webkit5
        - libwoff1
        - freeglut3
        parse-info:
        - usr/share/metainfo/org.kde.kdevelop.appdata.xml
        source: http://download.kde.org/stable/release-service/22.04.0/src/kdevelop-22.04.0.tar.xz
        cmake-parameters:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;/root/stage\\;/snap/kde-frameworks-5-qt-5-15-3-core20-sdk/current"
