---
name: kdevelop
confinement: strict
grade: stable
base: core20
adopt-info: kdevelop
apps:
  kdevelop:
    extensions:
    - kde-neon
    command: usr/bin/kdevelop
    plugs:
    - home
    - network
    - network-bind
    - audio-playback
    - removable-media
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
slots:
  session-dbus-interface:
    interface: dbus
    name: org.kde.kdevelop
    bus: session
parts:
  kdevelop:
    plugin: cmake
    build-packages:
    - libboost-dev
    - libastyle-dev
    - kdevelop-pg-qt
    - libkf5doctools-dev
    - libclang-11-dev
    - libgrantlee5-dev
    - libkomparediff2-dev
    - libsvn-dev
    - llvm-11-dev
    - llvm-11
    - okteta-dev
    - libkf5purpose-dev
    - libkf5sysguard-dev
    stage-packages:
    - libgrantlee-templates5
    - libgrantlee-textdocument5
    - libapr1
    - libaprutil1
    - libastyle3
    - libclang1-11
    - libclang-11-dev
    - libkasten4controllers0
    - libkasten4core0
    - libkasten4gui0
    - libkasten4okteta2controllers0
    - libkasten4okteta2core0
    - libkasten4okteta2gui0
    - libkomparediff2-5
    - libokteta3core0
    - libokteta3gui0
    - libqca-qt5-2
    - libserf-1-1
    - libsvn1
    - libutf8proc2
    - llvm-11-dev
    - libkf5purpose5
    - libksysguardformatter1
    - libprocesscore9
    - libprocessui9
    parse-info:
    - usr/share/metainfo/org.kde.kdevelop.appdata.xml
    source: http://download.kde.org/stable/kdevelop/5.6.2/src/kdevelop-5.6.2.tar.xz
    cmake-parameters:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;/root/stage\\;/snap/kde-frameworks-5-qt-5-15-core20-sdk/current"
