# Security rebuild 1
---
name: haruna
confinement: strict
grade: stable
base: core22
adopt-info: haruna
apps:
    haruna:
        # extensions:
        # - kde-neon
        common-id: org.kde.haruna
        desktop: usr/share/applications/org.kde.haruna.desktop
        command: usr/bin/haruna
        plugs:
        - desktop
        - desktop-legacy
        - opengl
        - wayland
        - x11
        - home
        - network
        - network-bind
        - audio-playback
        - removable-media
        - alsa
        - unity7
        command-chain:
        - snap/command-chain/desktop-launch
assumes:
- snapd2.55.3
compression: lzo
plugs:
    desktop:
        mount-host-font-cache: false
    icon-themes:
        interface: content
        target: $SNAP/data-dir/icons
        default-provider: gtk-common-themes
    sound-themes:
        interface: content
        target: $SNAP/data-dir/sounds
        default-provider: gtk-common-themes
    kf5-5-108-qt-5-15-10-core22:
        content: kf5-5-108-qt-5-15-10-core22-all
        interface: content
        default-provider: kf5-5-108-qt-5-15-10-core22
        target: $SNAP/kf5
environment:
    SNAP_DESKTOP_RUNTIME: $SNAP/kf5
    GST_PLUGIN_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0
    GST_PLUGIN_SYSTEM_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0
    GST_PLUGIN_SCANNER: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner
    XDG_DATA_DIRS: $SNAP/current/usr/share:/snap/kf5-5-108-qt-5-15-10-core22/current/usr/share:/usr/share${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}
    QT_PLUGIN_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/qt5/plugins:$SNAP/kf5/usr/lib/$CRAFT_ARCH_TRIPLET/qt5/plugins
    QML2_IMPORT_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/qt5/qml:$SNAP/kf5/usr/lib/$CRAFT_ARCH_TRIPLET/qt5/qml
    LD_LIBRARY_PATH: "$SNAP/usr/lib:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/lapack"
    QT_QUICK_CONTROLS_STYLE: org.kde.breeze.impl
hooks:
    configure:
        plugs:
        - desktop
        command-chain:
        - snap/command-chain/hooks-configure-desktop
layout:
    /usr/share/X11:
        symlink: $SNAP/kf5/usr/share/X11
    /usr/lib/$CRAFT_ARCH_TRIPLET/alsa-lib:
        symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/alsa-lib
    /usr/share/alsa:
        symlink: $SNAP/usr/share/alsa
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.haruna
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - jammy
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    kde-neon:
        source: /snap/snapcraft/current/share/snapcraft/extensions/desktop/kde-neon
        source-type: local
        plugin: make
        make-parameters:
        - PLATFORM_PLUG=kf5-5-108-qt-5-15-10-core22
        build-snaps:
        - kf5-5-108-qt-5-15-10-core22-sdk
        build-environment:
        - &id001
            PATH: /snap/kf5-5-108-qt-5-15-10-core22-sdk/current/usr/bin${PATH:+:$PATH}
        - &id002
            XDG_DATA_DIRS: $CRAFT_STAGE/usr/share:/snap/kf5-5-108-qt-5-15-10-core22-sdk/current/usr/share:/usr/share${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}
        - &id003
            XDG_CONFIG_HOME: $CRAFT_STAGE/etc/xdg:/snap/kf5-5-108-qt-5-15-10-core22-sdk/current/etc/xdg:/etc/xdg${XDG_CONFIG_HOME:+:$XDG_CONFIG_HOME}
        - &id004
            CRAFT_CMAKE_ARGS: -DCMAKE_FIND_ROOT_PATH=/snap/kf5-5-108-qt-5-15-10-core22-sdk/current${CRAFT_CMAKE_ARGS:+:$CRAFT_CMAKE_ARGS}
    haruna:
        after:
        - kde-neon
        parse-info:
        - usr/share/metainfo/org.kde.haruna.metainfo.xml
        plugin: cmake
        build-packages:
        - cmake
        - libswscale-dev
        - libmpv-dev
        - libavutil-dev
        - libavfilter-dev
        - libavcodec-dev
        - kirigami2-dev
        - libkf5doctools-dev
        - samba-dev
        - qtbase5-private-dev
        stage-packages:
        - libasound2
        - libasound2-data
        - libasound2-plugins
        - phonon4qt5
        - libgstreamer1.0-0
        - gstreamer1.0-alsa
        - gstreamer1.0-pulseaudio
        - gstreamer1.0-plugins-good
        - gstreamer1.0-plugins-bad
        - gstreamer1.0-plugins-ugly
        - phonon4qt5-backend-gstreamer
        - oxygen-sounds
        - libqt5gstreamer-1.0-0
        - libqt5gstreamerquick-1.0-0
        - libqt5gstreamerui-1.0-0
        - libqt5gstreamerutils-1.0-0
        - youtube-dl
        - libavdevice58
        - libavfilter7
        - libbs2b0
        - libcdio-cdda2
        - libcdio-paranoia2
        - libcdio19
        - libfftw3-double3
        - libflite1
        - libjansson4
        - libldb2
        - liblilv-0-0
        - libmpv1
        - libnorm1
        - libpgm-5.3-0
        - librubberband2
        - libsdl2-2.0-0
        - libserd-0-0
        - libsmbclient
        - libsodium23
        - libsord-0-0
        - libsratom-0-0
        - libtalloc2
        - libtevent0
        - libuchardet0
        - libvidstab1.1
        - libwbclient0
        - libxcursor1
        - libxinerama1
        - libzmq5
        - samba-libs
        - libblas3
        - liblapack3
        - qml-module-org-kde-breeze
        - libnvidia-gl-525
        source: https://download.kde.org/stable/haruna/haruna-0.12.0.tar.xz
        cmake-parameters:
        - -DCMAKE_INSTALL_PREFIX=/usr
        - -DCMAKE_BUILD_TYPE=Release
        - -DENABLE_TESTING=OFF
        - -DBUILD_TESTING=OFF
        - -DKDE_SKIP_TEST_SETTINGS=ON
        - -DCMAKE_FIND_ROOT_PATH=$CRAFT_STAGE\;/snap/kf5-5-108-qt-5-15-10-core22-sdk/current
        prime:
        - "-usr/lib/*/cmake/*"
        - "-usr/include/*"
        - "-usr/share/ECM/*"
        - "-usr/share/doc/*"
        - "-usr/share/man/*"
        - "-usr/share/icons/breeze-dark*"
        - "-usr/bin/X11"
        - "-usr/lib/gcc/$CRAFT_ARCH_TRIPLET/6.0.0"
        - "-usr/lib/aspell/*"
        build-environment: &id005
        - *id001
        - *id002
        - *id003
        - *id004
