---
name: kstars
version: 3.5.7
confinement: strict
grade: devel
base: core20
adopt-info: kstars
apps:
    kstars:
        extensions:
        - kde-neon
        common-id: org.kde.kstars.desktop
        command: usr/bin/kstars
        plugs:
        - home
        - network
        - network-bind
        - audio-playback
        - serial-port
        - camera
        - gpio
        - hardware-observe
        - hidraw
        - i2c
        - location-control
        - location-observe
        - raw-usb
        - removable-media
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.kstars
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    kstars:
        plugin: cmake
        build-packages:
        - libeigen3-dev
        - zlib1g-dev
        - libcfitsio-dev
        - libnova-dev
        - libgsl-dev
        - libindi-dev
        - qt5keychain-dev
        - wcslib-dev
        - gsc
        - libapogee3
        - libatik
        - libfishcamp
        - libfli2
        - libinovasdk
        - libnncam
        - libqhy
        - libqsi7
        - libaltaircam
        - libsbig
        - libstarshootg
        - libtoupcam
        - libstellarsolver-dev
        - libkf5doctools-dev
        - libraw-dev
        - libqt5datavisualization5-dev
        stage-packages:
        - libstellarsolver
        - astrometry.net
        - xplanet
        - libcfitsio8
        - libnova-0.16-0
        - libgsl23
        - libindialignmentdriver1
        - libindidriver1
        - libpgsbox7
        - libwcs7
        - libqt5keychain1
        - libsecret-1-dev
        - libglvnd0
        - libgomp1
        - gsc
        - libapogee3
        - libatik
        - libfishcamp
        - libfli2
        - libinovasdk
        - libnncam
        - libqhy
        - libqsi7
        - libaltaircam
        - libsbig
        - libstarshootg
        - libtoupcam
        - libqt5datavisualization5
        - libraw19
        parse-info:
        - usr/share/metainfo/org.kde.kstars.appdata.xml
        source: http://download.kde.org/stable/kstars/kstars-3.5.7.tar.xz
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;/root/stage\\;/snap/kde-frameworks-5-qt-5-15-3-core20-sdk/current"
