---
name: kstars
version: 3.5.4
confinement: strict
grade: devel
base: core20
adopt-info: kstars
apps:
    kstars:
        extensions:
        - kde-neon
        common-id: org.kde.kstars.desktop
        command: usr/bin/kstars
        plugs:
        - kde-frameworks-5-plug
        - home
        - network
        - network-bind
        - audio-playback
        - serial-port
        - camera
        - gpio
        - hardware-observe
        - hidraw
        - i2c
        - location-control
        - location-observe
        - raw-usb
        - removable-media
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.kstars
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 7DA5C2D272B4C6F8E7CEA9C6487CEC2B3F33A288
    url: http://ppa.launchpad.net/mutlaqja/ppa/ubuntu
    key-server: keyserver.ubuntu.com
parts:
    kstars:
        plugin: cmake
        build-environment:
        -   CMAKE_BUILD_PARALLEL_LEVEL: '4'
        build-packages:
        - libeigen3-dev
        - zlib1g-dev
        - libcfitsio-dev
        - libnova-dev
        - libgsl-dev
        - libindi-dev
        - qt5keychain-dev
        - wcslib-dev
        - gsc
        - indi-aagcloudwatcher
        - indi-apogee
        - indi-armadillo-platypus
        - indi-asi
        - indi-astromechfoc
        - indi-atik
        - indi-avalon
        - indi-dreamfocuser
        - indi-dsi
        - indi-duino
        - indi-eqmod
        - indi-ffmv
        - indi-fishcamp
        - indi-fli
        - indi-full
        - indi-gphoto
        - indi-gpsd
        - indi-gpsnmea
        - indi-inovaplx
        - indi-maxdomeii
        - indi-mgen
        - indi-mi
        - indi-nexdome
        - indi-nexstarevo
        - indi-nightscape
        - indi-qhy
        - indi-qsi
        - indi-sbig
        - indi-shelyak
        - indi-ssag
        - indi-starbook
        - indi-sx
        - indi-toupbase
        - indi-webcam
        - libapogee3
        - libatik
        - libfishcamp
        - libfli2
        - libinovasdk
        - libnncam
        - libqhy
        - libqsi7
        - libaltaircam
        - libsbig
        - libstarshootg
        - libtoupcam
        - libstellarsolver-dev
        - libkf5doctools-dev
        - libraw-dev
        - libqt5datavisualization5-dev
        stage-packages:
        - libstellarsolver
        - astrometry.net
        - indi-bin
        - xplanet
        - libcfitsio8
        - libnova-0.16-0
        - libgsl23
        - libindialignmentdriver1
        - libindidriver1
        - libpgsbox7
        - libwcs7
        - libqt5keychain1
        - libsecret-1-dev
        - libglvnd0
        - libgomp1
        - gsc
        - indi-aagcloudwatcher
        - indi-apogee
        - indi-armadillo-platypus
        - indi-asi
        - indi-astromechfoc
        - indi-atik
        - indi-avalon
        - indi-dreamfocuser
        - indi-dsi
        - indi-duino
        - indi-eqmod
        - indi-ffmv
        - indi-fishcamp
        - indi-fli
        - indi-full
        - indi-gphoto
        - indi-gpsd
        - indi-gpsnmea
        - indi-inovaplx
        - indi-maxdomeii
        - indi-mgen
        - indi-mi
        - indi-nexdome
        - indi-nexstarevo
        - indi-nightscape
        - indi-qhy
        - indi-qsi
        - indi-sbig
        - indi-shelyak
        - indi-ssag
        - indi-starbook
        - indi-sx
        - indi-toupbase
        - indi-webcam
        - libapogee3
        - libatik
        - libfishcamp
        - libfli2
        - libinovasdk
        - libnncam
        - libqhy
        - libqsi7
        - libaltaircam
        - libsbig
        - libstarshootg
        - libtoupcam
        - libqt5datavisualization5
        - libraw19
        parse-info:
        - usr/share/metainfo/org.kde.kstars.appdata.xml
        source: http://download.kde.org/stable/kstars/kstars-3.5.4.tar.xz
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;/root/stage\\;/snap/kde-frameworks-5-qt-5-15-core20-sdk/current"
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/x86_64-linux-gnu/6.0.0"
            - "-usr/lib/aspell/*"
        prime:
        - "$exclusion"
