---
name: kanagram
confinement: strict
grade: stable
base: core20
adopt-info: kanagram
apps:
    kanagram:
        extensions:
        - kde-neon
        common-id: org.kde.kanagram.desktop
        command: usr/bin/kanagram
        environment:
            GST_PLUGIN_SCANNER: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gstreamer-1.0/"
        plugs:
        - home
        - network
        - network-bind
        - audio-playback
        - removable-media
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.kanagram
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    kanagram:
        parse-info:
        - usr/share/metainfo/org.kde.kanagram.appdata.xml
        plugin: cmake
        build-packages:
        - libkeduvocdocument-dev
        - libphonon4qt5-dev
        - libphonon4qt5experimental-dev
        - libkf5doctools-dev
        stage-packages:
        - libkeduvocdocument5
        - gstreamer1.0-plugins-good
        - gstreamer1.0-plugins-base
        - gstreamer1.0-x
        source: http://download.kde.org/stable/release-service/22.08.0/src/kanagram-22.08.0.tar.xz
        cmake-parameters:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;/root/stage\\;/snap/kde-frameworks-5-96-qt-5-15-5-core20-sdk/current"
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/x86_64-linux-gnu/6.0.0"
            - "-usr/lib/aspell/*"
        prime:
        - "$exclusion"
version: 22.08.0
