---
name: ktuberling
confinement: strict
grade: stable
base: core20
adopt-info: ktuberling
apps:
    ktuberling:
        extensions:
        - kde-neon
        common-id: org.kde.ktuberling.desktop
        command: usr/bin/ktuberling
        environment:
            GST_PLUGIN_PATH: "$SNAP/usr/lib/x86_64-linux-gnu/gstreamer-1.0"
            GST_PLUGIN_SYSTEM_PATH: "$SNAP/usr/lib/x86_64-linux-gnu/gstreamer-1.0"
            GST_PLUGIN_SCANNER: "$SNAP/usr/lib/x86_64-linux-gnu/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner"
        plugs:
        - home
        - network
        - network-bind
        - audio-playback
        - removable-media
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.ktuberling
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    ktuberling:
        parse-info:
        - usr/share/metainfo/org.kde.ktuberling.appdata.xml
        plugin: cmake
        build-packages:
        - libkf5doctools-dev
        - libphonon4qt5-dev
        - libphonon4qt5experimental-dev
        stage-packages:
        - libgstreamer1.0-0
        - gstreamer1.0-plugins-good
        source: http://download.kde.org/stable/release-service/22.04.2/src/ktuberling-22.04.2.tar.xz
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;/root/stage\\;/snap/kde-frameworks-5-91-qt-5-15-3-core20-sdk/current"
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/x86_64-linux-gnu/6.0.0"
            - "-usr/lib/aspell/*"
        prime:
        - "$exclusion"
version: 22.04.2
