---
name: kjournald
confinement: strict
grade: stable
version: 0.0.3
base: core20
adopt-info: kjournald
apps:
    kjournaldbrowser:
        extensions:
        - kde-neon
        common-id: org.kde.kjournaldbrowser.desktop
        command: usr/bin/kjournaldbrowser
        plugs:
        - home
        - network
        - network-bind
        - log-observe
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    kjournald:
        parse-info:
        - usr/share/metainfo/org.kde.kjournaldbrowser.appdata.xml
        plugin: cmake
        build-packages:
        - libsystemd-dev
        - pkg-config
        stage-packages:
        - oxygen-icon-theme
        source: https://download.kde.org/stable/kjournald/kjournald-0.1.0.tar.xz
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$SNAPCRAFT_STAGE\\;/snap/kde-frameworks-5-99-qt-5-15-7-core20-sdk/current"
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=FALSE"
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/$SNAPCRAFT_ARCH_TRIPLET/6.0.0"
            - "-usr/lib/aspell/*"
        prime:
        - "$exclusion"
    cleanup:
        after:
        - kjournald
        plugin: nil
        build-snaps:
        - kde-frameworks-5-99-qt-5-15-7-core20
        override-prime: |
            set -eux
            for snap in "kde-frameworks-5-99-qt-5-15-7-core20"; do  # List all content-snaps you're using here
                cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" "$SNAPCRAFT_PRIME/usr/{}" \;
            done
            find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
