---
name: spectacle
confinement: strict
grade: stable
base: core20
adopt-info: spectacle
apps:
    spectacle:
        extensions:
        - kde-neon
        common-id: org.kde.spectacle.desktop
        command: usr/bin/spectacle
        plugs:
        - home
        - opengl
        - network
        - audio-playback
        - removable-media
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.spectacle
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    spectacle:
        parse-info:
        - usr/share/metainfo/org.kde.spectacle.appdata.xml
        plugin: cmake
        build-packages:
        - libxcb-cursor-dev
        - libxcb-image0-dev
        - libxcb-util0-dev
        - libxcb-xfixes0-dev
        - libkimageannotator-dev
        - libkf5kipi-dev
        - libkf5doctools-dev
        - libkf5purpose-dev
        - libkf5newstuff-dev
        - libkf5screen-dev
        source: http://download.kde.org/stable/release-service/22.08.0/src/spectacle-22.08.0.tar.xz
        override-stage: |
            snapcraftctl stage
            rm $SNAPCRAFT_STAGE/usr/share/kglobalaccel/org.kde.spectacle.desktop
            ln -s ../applications/org.kde.spectacle.desktop $SNAPCRAFT_STAGE/usr/share/kglobalaccel/org.kde.spectacle.desktop
        stage-packages:
        - kio
        - libxcb-image0
        - libxcb-cursor0
        - libxcb-util1
        - libxcb-xfixes0
        - libkf5kipi32.0.0
        - kipi-plugins-common
        - kipi-plugins
        - libkimageannotator0
        - libkcolorpicker0
        - libkf5purpose5
        cmake-parameters:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$SNAPCRAFT_STAGE\\;/snap/kde-frameworks-5-96-qt-5-15-5-core20-sdk/current"
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/$SNAPCRAFT_ARCH_TRIPLET/6.0.0"
            - "-usr/lib/aspell/*"
        prime:
        - "$exclusion"
version: 22.08.0
