---
name: gwenview
confinement: strict
grade: stable
base: core20
adopt-info: gwenview
apps:
    gwenview:
        extensions:
        - kde-neon
        common-id: org.kde.gwenview.desktop
        command: usr/bin/gwenview
        plugs:
        - home
        - network
        - network-bind
        - audio-playback
        - removable-media
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.gwenview
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    gwenview:
        parse-info:
        - usr/share/metainfo/org.kde.gwenview.appdata.xml
        plugin: cmake
        build-packages:
        - libexiv2-dev
        - libjpeg-dev
        - libkf5kdcraw-dev
        - libkf5kipi-dev
        - liblcms2-dev
        - libcfitsio-dev
        - libphonon4qt5-dev
        - libphonon4qt5experimental-dev
        - libpng-dev
        - libkf5doctools-dev
        - libkf5purpose-dev
        - libtiff-dev
        stage-packages:
        - libkf5kdcraw5
        - libkf5kipi32.0.0
        - libcfitsio8
        - libkf5purpose5
        - libkf5purpose-bin
        source: http://download.kde.org/stable/release-service/22.04.2/src/gwenview-22.04.2.tar.xz
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;/root/stage\\;/snap/kde-frameworks-5-91-qt-5-15-3-core20-sdk/current"
        - "-DKDE_INSTALL_PLUGINDIR=/usr/lib/x86_64-linux-gnu/qt5/plugins/"
version: 22.04.2
