---
name: gwenview
confinement: strict
grade: stable
base: core20
adopt-info: gwenview
apps:
    gwenview:
        common-id: org.kde.gwenview.desktop
        command: kf5-launch gwenview
        plugs:
        - kde-frameworks-5-plug
        - home
        - x11
        - opengl
        - network
        - network-bind
        - audio-playback
        - desktop
        - desktop-legacy
        - removable-media
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.gwenview
        bus: session
plugs:
    kde-frameworks-5-plug:
        content: kde-frameworks-5-qt-5-15-core20-all
        interface: content
        default-provider: kde-frameworks-5-qt-5-15-core20
        target: kf5
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    gwenview:
        parse-info:
        - usr/share/metainfo/org.kde.gwenview.appdata.xml
        build-snaps:
        - kde-frameworks-5-qt-5-15-core20-sdk/latest/candidate
        after:
        - kde-frameworks-5-env
        plugin: cmake
        build-environment:
        -   CMAKE_BUILD_PARALLEL_LEVEL: '4'
        build-packages:
        - libexiv2-dev
        - libjpeg-dev
        - libkf5kdcraw-dev
        - libkf5kipi-dev
        - liblcms2-dev
        - libcfitsio-dev
        - libphonon4qt5-dev
        - libphonon4qt5experimental-dev
        - libpng-dev
        - libkf5doctools-dev
        - libkf5purpose-dev
        - libtiff-dev
        stage-packages:
        - libkf5kdcraw5
        - libkf5kipi32.0.0
        - libcfitsio8
        - libkf5purpose5
        - libkf5purpose-bin
        source: http://download.kde.org/stable/release-service/21.08.0/src/gwenview-21.08.0.tar.xz
        cmake-parameters:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;/root/stage\\;/snap/kde-frameworks-5-qt-5-15-core20-sdk/current"
        - "-DKDE_INSTALL_PLUGINDIR=/usr/lib/x86_64-linux-gnu/qt5/plugins/"
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/x86_64-linux-gnu/6.0.0"
            - "-usr/lib/aspell/*"
        prime:
        - "$exclusion"
    kde-frameworks-5-env:
        plugin: dump
        source: https://invent.kde.org/packaging/snap-kf5-launcher.git
