---
name: gwenview
confinement: strict
grade: stable
base: core20
adopt-info: gwenview
apps:
    gwenview:
        extensions:
        - kde-neon
        common-id: org.kde.gwenview.desktop
        command: usr/bin/gwenview
        plugs:
        - home
        - network
        - network-bind
        - audio-playback
        - removable-media
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.gwenview
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    gwenview:
        parse-info:
        - usr/share/metainfo/org.kde.gwenview.appdata.xml
        plugin: cmake
        build-packages:
        - libexiv2-dev
        - libjpeg-dev
        - libkf5kdcraw-dev
        - libkf5kipi-dev
        - libkimageannotator-dev
        - liblcms2-dev
        - libcfitsio-dev
        - libphonon4qt5-dev
        - libphonon4qt5experimental-dev
        - libpng-dev
        - libkf5doctools-dev
        - libkf5purpose-dev
        - libtiff-dev
        stage-packages:
        - libkf5kdcraw5
        - libkf5kipi32.0.0
        - libcfitsio8
        - libkf5purpose5
        - libkf5purpose-bin
        source: http://download.kde.org/stable/release-service/22.08.0/src/gwenview-22.08.0.tar.xz
        cmake-parameters:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$SNAPCRAFT_STAGE\\;/snap/kde-frameworks-5-96-qt-5-15-5-core20-sdk/current"
        - "-DKDE_INSTALL_PLUGINDIR=/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/plugins/"
version: 22.08.0
