#!/bin/bash
#
# Copyright (C) 2019 Jonathan Riddell <jr@jriddell.org>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 3 of
# the License or any later version accepted by the membership of
# KDE e.V. (or its successor approved by the membership of KDE
# e.V.), which shall act as a proxy defined in Section 14 of
# version 3 of the license.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if [ "$SNAP_ARCH" == "amd64" ]; then
  ARCH='x86_64-linux-gnu'
elif [ "$SNAP_ARCH" == "armhf" ]; then
  ARCH="arm-linux-gnueabihf"
else
  ARCH="$SNAP_ARCH-linux-gnu"
fi

export MLT_REPOSITORY=$SNAP/usr/lib/$ARCH/mlt/
export MLT_DATA=$SNAP/usr/share/mlt/
export MLT_ROOT_DIR=$SNAP/usr/
export LADSPA_PATH=$SNAP/usr/lib/ladspa
export FREI0R_PATH=$SNAP/usr/lib/frei0r-1
export MLT_PROFILES_PATH=$SNAP/usr/share/mlt/profiles/
export MLT_PRESETS_PATH=$SNAP/usr/share/mlt/presets/
export SDL_AUDIODRIVER=pulseaudio
export XDG_CURRENT_DESKTOP=

exec "$@"
