---
name: kalgebra
confinement: strict
grade: stable
base: core20
adopt-info: kalgebra
apps:
    kalgebra:
        extensions:
        - kde-neon
        common-id: org.kde.kalgebra.desktop
        command: usr/bin/kalgebra
        plugs:
        - home
        - network
        - network-bind
        - audio-playback
        - browser-support
        - removable-media
layout:
    "/usr/share/qt5":
        symlink: "$SNAP/kf5/usr/share/qt5"
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    analitza:
        plugin: cmake
        build-packages:
        - libncurses-dev
        - libreadline-dev
        - libgl-dev
        - libeigen3-dev
        stage-packages:
        - libncurses6
        - libreadline8
        - libgl1
        - libglx0
        source: https://download.kde.org/stable/release-service/21.12.1/src/analitza-21.12.1.tar.xz
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$SNAPCRAFT_STAGE\\;/snap/kde-frameworks-5-98-qt-5-15-6-core20-sdk/current"
    kalgebra:
        parse-info:
        - usr/share/metainfo/org.kde.kalgebra.appdata.xml
        after:
        - analitza
        plugin: cmake
        build-packages:
        - libncurses-dev
        - libreadline-dev
        - libkf5doctools-dev
        stage-packages:
        - libncurses6
        - libreadline8
        source: http://download.kde.org/stable/release-service/22.08.1/src/kalgebra-22.08.1.tar.xz
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$SNAPCRAFT_STAGE\\;/snap/kde-frameworks-5-98-qt-5-15-6-core20-sdk/current"
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/$SNAPCRAFT_ARCH_TRIPLET/6.0.0"
            - "-usr/lib/aspell/*"
        prime:
        - "$exclusion"
version: 22.08.1
