name: kopete
adopt-info: kopete
confinement: strict
grade: stable
base: core22
version: 23.04.0
apps:
    kopete:
        common-id: org.kde.kopete.desktop
        command: usr/bin/kopete
        plugs:
        - home
        - desktop
        - desktop-legacy
        - opengl
        - wayland
        - x11
        - audio-playback
        - unity7
        - network
        - network-bind
        command-chain:
        - snap/command-chain/desktop-launch
assumes:
- snapd2.43
compression: lzo
plugs:
    desktop:
        mount-host-font-cache: false
    icon-themes:
        interface: content
        target: $SNAP/data-dir/icons
        default-provider: gtk-common-themes
    sound-themes:
        interface: content
        target: $SNAP/data-dir/sounds
        default-provider: gtk-common-themes
    kf5-5-105-qt-5-15-9-core22:
        content: kf5-5-105-qt-5-15-9-core22-all
        interface: content
        default-provider: kf5-5-105-qt-5-15-9-core22
        target: $SNAP/kf5
environment:
    SNAP_DESKTOP_RUNTIME: $SNAP/kf5
hooks:
    configure:
        plugs:
        - desktop
        command-chain:
        - snap/command-chain/hooks-configure-desktop
layout:
    /usr/share/X11:
        symlink: $SNAP/kf5/usr/share/X11
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - jammy
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    kde-neon:
        source: /snap/snapcraft/current/share/snapcraft/extensions/desktop/kde-neon
        source-type: local
        plugin: make
        make-parameters:
        - PLATFORM_PLUG=kf5-5-105-qt-5-15-9-core22
        build-snaps:
        - kf5-5-105-qt-5-15-9-core22-sdk
        build-environment:
        - &id001
            PATH: /snap/kf5-5-105-qt-5-15-9-core22-sdk/current/usr/bin${PATH:+:$PATH}
        - &id002
            XDG_DATA_DIRS: $CRAFT_STAGE/usr/share:/snap/kf5-5-105-qt-5-15-9-core22-sdk/current/usr/share:/usr/share${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}
        - &id003
            LD_LIBRARY_PATH: /snap/kf5-5-105-qt-5-15-9-core22-sdk/current/lib/$CRAFT_ARCH_TRIPLET:/snap/kf5-5-105-qt-5-15-9-core22-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET:/snap/kf5-5-105-qt-5-15-9-core22-sdk/current/usr/lib:/snap/kf5-5-105-qt-5-15-9-core22-sdk/current/usr/lib/vala-current:/snap/kf5-5-105-qt-5-15-9-core22-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/pulseaudio${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
        - &id004
            PKG_CONFIG_PATH: /snap/kf5-5-105-qt-5-15-9-core22-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig:/snap/kf5-5-105-qt-5-15-9-core22-sdk/current/usr/lib/pkgconfig:/snap/kf5-5-105-qt-5-15-9-core22-sdk/current/usr/share/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
        - &id005
            ACLOCAL_PATH: /snap/kf5-5-105-qt-5-15-9-core22-sdk/current/usr/share/aclocal${ACLOCAL_PATH:+:$ACLOCAL_PATH}
        - &id006
            SNAPCRAFT_CMAKE_ARGS: -DCMAKE_FIND_ROOT_PATH=/snap/kf5-5-105-qt-5-15-9-core22-sdk/current${SNAPCRAFT_CMAKE_ARGS:+:$SNAPCRAFT_CMAKE_ARGS}
    ktextaddons:
        after:
        - kde-neon
        - psmisc
        plugin: cmake
        build-packages:
        - cmake
        source: https://invent.kde.org/libraries/ktextaddons.git
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$CRAFT_STAGE\\;/snap/kf5-5-105-qt-5-15-9-core22-sdk/current"
        - "-DKDE_INSTALL_PLUGINDIR=/usr/lib/$CRAFT_ARCH_TRIPLET/qt5/plugins/"
        prime:
        - "-usr/lib/*/cmake/*"
        - "-usr/include/*"
        - "-usr/share/ECM/*"
        - "-usr/share/doc/*"
        - "-usr/share/man/*"
        - "-usr/share/icons/breeze-dark*"
        - "-usr/bin/X11"
        - "-usr/lib/gcc/$CRAFT_ARCH_TRIPLET/6.0.0"
        - "-usr/lib/aspell/*"
        - "-usr/share/lintain"
        build-environment: &id007
        - *id001
        - *id002
        - *id003
        - *id004
        - *id005
        - *id006
    kopete:
        after:
        - kde-neon
        - ktextaddons
        parse-info:
        - usr/share/metainfo/org.kde.kopete.appdata.xml
        source: http://download.kde.org/stable/release-service/23.04.0/src/kopete-23.04.0.tar.xz
        plugin: cmake
        build-packages:
        - cmake
        - libkf5doctools-dev
        - libkf5contacts-dev
        - libkf5identitymanagement-dev
        - libphonon4qt5-dev
        - libphonon4qt5experimental-dev
        stage-packages:
        - libkf5contacts5
        - libkf5identitymanagement5
        - phonon4qt5
        cmake-parameters:
        - -DKDE_INSTALL_USE_QT_SYS_PATHS=FALSE
        - -DCMAKE_INSTALL_PREFIX=/usr
        - -DCMAKE_BUILD_TYPE=Release
        - -DENABLE_TESTING=OFF
        - -DBUILD_TESTING=OFF
        - -DKDE_SKIP_TEST_SETTINGS=ON
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$CRAFT_STAGE\\;/snap/kf5-5-105-qt-5-15-9-core22-sdk/current"
        - "-DKDE_INSTALL_PLUGINDIR=/usr/lib/$CRAFT_ARCH_TRIPLET/qt5/plugins/"
        prime:
        - "-usr/lib/*/cmake/*"
        - "-usr/include/*"
        - "-usr/share/ECM/*"
        - "-usr/share/doc/*"
        - "-usr/share/man/*"
        - "-usr/share/icons/breeze-dark*"
        - "-usr/bin/X11"
        - "-usr/lib/gcc/$CRAFT_ARCH_TRIPLET/6.0.0"
        - "-usr/lib/aspell/*"
        - "-usr/share/lintain"
        build-environment: *id007
    cleanup:
        after:
        - kde-neon
        - kopete
        plugin: nil
        build-snaps:
        - kf5-5-105-qt-5-15-9-core22-sdk
        override-prime:  |
            set -eux
            find $CRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
            find $CRAFT_PRIME/usr/share -type d -empty -delete
            # # Unused libraries found by linter

