---
name: skrooge
version: 2.28.0
adopt-info: skrooge
confinement: strict
grade: stable
base: core20
apps:
    skrooge:
        extensions:
        - kde-neon
        command: usr/bin/skrooge
        common-id: org.kde.skrooge
        desktop: org.kde.skrooge.desktop
        plugs:
        - home
        - network
        - network-bind
        - network-manager
        - audio-playback
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.skrooge
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    skrooge:
        plugin: cmake
        build-packages:
        - libgrantlee5-dev
        - libofx-dev
        - libqca-qt5-2-dev
        - libsqlcipher-dev
        - xsltproc
        - qtbase5-private-dev
        - docbook-xml
        - docbook-xsl
        - libkf5doctools-dev
        stage-packages:
        - libgrantlee-templates5
        - libgrantlee-textdocument5
        - libofx7
        - libqca-qt5-2
        - libsqlcipher0
        - freeglut3
        - libslang2
        source: https://download.kde.org/stable/skrooge/skrooge-2.28.0.tar.xz
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$SNAPCRAFT_STAGE\\;/snap/kde-frameworks-5-100-qt-5-15-7-core20-sd/current"
        parse-info:
        - usr/share/metainfo/org.kde.skrooge.appdata.xml
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/$SNAPCRAFT_ARCH_TRIPLET/6.0.0"
            - "-usr/lib/aspell/*"
        prime:
        - "$exclusion"
