---
name: kajongg
confinement: strict
grade: stable
base: core20
adopt-info: kajongg
apps:
    kajongg:
        extensions:
        - kde-neon
        common-id: org.kde.kajongg.desktop
        command: usr/bin/kajongg
        plugs:
        - home
        - network
        - network-bind
        - audio-playback
        - removable-media
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.kajongg
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    kajongg:
        parse-info:
        - usr/share/metainfo/org.kde.kajongg.appdata.xml
        plugin: cmake
        build-packages:
        - libkf5kmahjongglib-dev
        - libkf5doctools-dev
        - python3
        - python3-twisted
        stage-packages:
        - libkf5kmahjongglib5
        - kdegames-mahjongg-data-kf5
        - python3
        - python3-twisted
        - python3-pyqt5.qtsvg
        - python3-pyqt5
        source: http://download.kde.org/stable/release-service/22.08.2/src/kajongg-22.08.2.tar.xz
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$SNAPCRAFT_STAGE\\;/snap/kde-frameworks-5-98-qt-5-15-6-core20-sdk/current"
        override-build: |
            snapcraftctl build
            rm $SNAPCRAFT_PART_INSTALL/usr/bin/kajongg
            cp $SNAPCRAFT_PART_INSTALL/usr/share/kajongg/kajongg.py $SNAPCRAFT_PART_INSTALL/usr/bin/kajongg
            rm $SNAPCRAFT_PART_INSTALL/usr/bin/kajonggserver
            cp $SNAPCRAFT_PART_INSTALL/usr/share/kajongg/kajonggserver.py $SNAPCRAFT_PART_INSTALL/usr/bin/kajonggserver
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/$SNAPCRAFT_ARCH_TRIPLET/6.0.0"
            - "-usr/lib/aspell/*"
        prime:
        - "$exclusion"
version: 22.08.2
