---
name: kate
confinement: classic
grade: stable
base: core22
adopt-info: kate
apps:
    kate:
        # extensions:
        # - kde-neon
        command: usr/bin/kate
        common-id: org.kde.kate.desktop
        command-chain:
        - snap/command-chain/desktop-launch
assumes:
- snapd2.43
compression: lzo
environment:
    SNAP_DESKTOP_RUNTIME: $SNAP/kf5
    QTWEBENGINEPROCESS_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/qt5/libexec/QtWebEngineProcess"
    XDG_DATA_DIRS: "$XDG_DATA_DIRS:$SNAP/usr/share"
    XDG_CONFIG_DIRS: "$XDG_CONFIG_DIRS:$SNAP/etc/xdg"
    __EGL_VENDOR_LIBRARY_DIRS: "$SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d"
    LIBGL_DRIVERS_PATH: "$SNAP/usr/lib/${CRAFT_ARCH_TRIPLET}/dri"
hooks:
    configure:
        plugs:
        - desktop
        command-chain:
        - snap/command-chain/hooks-configure-desktop
layout:
    /usr/share/X11:
        symlink: $SNAP/kf5/usr/share/X11
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - jammy
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    mesa-patchelf:
        plugin: nil
        stage-packages:
        - libgl1-mesa-dri
        - freeglut3
        - libglu1-mesa
        stage:
        - "-usr/lib/${CRAFT_ARCH_TRIPLET}/dri"
    mesa-no-patchelf:
        plugin: nil
        stage-packages:
        - libgl1-mesa-dri
        build-attributes:
        - no-patchelf
        stage:
        - usr/lib/${CRAFT_ARCH_TRIPLET}/dri
    qtconf:
        plugin: nil
        override-build: |
            mkdir -p $CRAFT_PART_INSTALL/usr/bin
            cat <<EOF > $CRAFT_PART_INSTALL/usr/bin/qt.conf
            [Paths]
            Prefix = ../../
            LibraryExecutables = usr/lib/$CRAFT_ARCH_TRIPLET/qt5/libexec
            Plugins = usr/lib/$CRAFT_ARCH_TRIPLET/qt5/plugins
            Qml2Imports = usr/lib/$CRAFT_ARCH_TRIPLET/qt5/qml
            Translations = usr/share/qt5/translations
            Data = usr/share/qt5
            EOF
    kate:
        after:
        - mesa-patchelf
        - mesa-no-patchelf
        - qtconf
        parse-info:
        - usr/share/metainfo/org.kde.kate.appdata.xml
        plugin: cmake
        build-packages:
        - cmake
        - libgit2-dev
        - libkf5doctools-dev
        - gettext
        - libeditorconfig-dev
        - extra-cmake-modules
        - libkf5i18n-dev
        - libkf5textwidgets-dev
        - libkf5texteditor-dev
        - libkf5coreaddons-dev
        - libkf5syntaxhighlighting-dev
        - libkf5crash-dev
        stage-packages:
        - libgit2-1.1
        - konsole-kpart
        - libeditorconfig0
        - hspell
        - libkf5kiofilewidgets5
        - libkf5syntaxhighlighting5
        - libkf5texteditor5
        - libqt5concurrent5
        source: http://download.kde.org/stable/release-service/22.12.3/src/kate-22.12.3.tar.xz
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$CRAFT_STAGE\\;/snap/kf5-5-104-qt-5-15-8-core22-sdk/current"
        prime:
        - "-usr/lib/*/cmake/*"
        - "-usr/include/*"
        - "-usr/share/ECM/*"
        - "-usr/share/doc/*"
        - "-usr/share/man/*"
        - "-usr/share/icons/breeze-dark*"
        - "-usr/bin/X11"
        - "-usr/lib/gcc/$CRAFT_ARCH_TRIPLET/6.0.0"
        - "-usr/lib/aspell/*"
        build-environment: &id007
        - *id001
        - *id002
        - *id003
        - *id004
        - *id005
        - *id006
version: 22.12.3
