---
name: kate
confinement: classic
grade: stable
base: core20
adopt-info: kate
apps:
    kate:
        command: usr/bin/kate
        environment:
            QT_PLUGIN_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/plugins:$SNAPCRAFT_ARCH_TRIPLET/usr/lib/x86_64-linux-gnu"
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    kate:
        parse-info:
        - usr/share/metainfo/org.kde.kate.appdata.xml
        plugin: cmake
        build-packages:
        - libgit2-dev
        - libkf5doctools-dev
        - extra-cmake-modules
        - libkf5i18n-dev
        - libkf5textwidgets-dev
        - libkf5texteditor-dev
        - libkf5coreaddons-dev
        - libkf5syntaxhighlighting-dev
        - libkf5crash-dev
        - gettext
        stage-packages:
        - libgit2-28
        - konsole-kpart
        - libeditorconfig0
        - libglu1-mesa
        - libkf5kiofilewidgets5
        - libkf5syntaxhighlighting5
        - libkf5texteditor5
        - libqt5concurrent5
        - freeglut3
        - hspell
        source: http://download.kde.org/stable/release-service/22.04.1/src/kate-22.04.1.tar.xz
        cmake-parameters:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;/root/stage"
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/x86_64-linux-gnu/6.0.0"
            - "-usr/lib/aspell/*"
        prime:
        - "$exclusion"
version: 22.04.1
