---
name: kate
confinement: classic
grade: stable
base: core20
adopt-info: kate
compression: lzo
apps:
    kate:
        command: usr/bin/kate
        common-id: org.kde.kate.desktop
        environment:
            QT_PLUGIN_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/plugins:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
            QTWEBENGINEPROCESS_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/libexec/QtWebEngineProcess
            XDG_DATA_DIRS: $XDG_DATA_DIRS:$SNAP/usr/share
            XDG_CONFIG_DIRS: $XDG_CONFIG_DIRS:$SNAP/etc/xdg
            __EGL_VENDOR_LIBRARY_DIRS: $SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d
            LIBGL_DRIVERS_PATH: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    mesa-patchelf:
      plugin: nil
      stage-packages:
        - libgl1-mesa-dri
        - freeglut3
        - libglu1-mesa
      stage:
        - -usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
    mesa-no-patchelf:
      plugin: nil
      stage-packages:
        - libgl1-mesa-dri
      build-attributes:
        - no-patchelf
      stage:
        - usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
    kate:
        parse-info:
        - usr/share/metainfo/org.kde.kate.appdata.xml
        plugin: cmake
        build-packages:
        - libgit2-dev
        - libkf5doctools-dev
        - extra-cmake-modules
        - libkf5i18n-dev
        - libkf5textwidgets-dev
        - libkf5texteditor-dev
        - libkf5coreaddons-dev
        - libkf5syntaxhighlighting-dev
        - libkf5crash-dev
        - gettext
        stage-packages:
        - libgit2-28
        - konsole-kpart
        - libeditorconfig0
        - libkf5kiofilewidgets5
        - libkf5syntaxhighlighting5
        - libkf5texteditor5
        - libqt5concurrent5
        - hspell
        source: http://download.kde.org/stable/release-service/22.04.3/src/kate-22.04.3.tar.xz
        cmake-parameters:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$SNAPCRAFT_STAGE"
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/$SNAPCRAFT_ARCH_TRIPLET/6.0.0"
            - "-usr/lib/aspell/*"
        prime:
        - "$exclusion"
