---
name: ktouch
confinement: strict
grade: stable
base: core20
adopt-info: ktouch
apps:
    ktouch:
        extensions:
        - kde-neon
        common-id: org.kde.ktouch.desktop
        command: usr/bin/ktouch
        plugs:
        - home
        - network
        - network-bind
        - audio-playback
        - removable-media
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    ktouch:
        parse-info:
        - usr/share/metainfo/org.kde.ktouch.appdata.xml
        plugin: cmake
        build-packages:
        - libxcb-xkb-dev
        - libxkbfile-dev
        - libkf5doctools-dev
        stage-packages:
        - qml-module-org-kde-charts
        - libxcb-xkb1
        - libxkbfile1
        - qml-module-org-kde-kcoreaddons
        - qml-module-org-kde-kquickcontrolsaddons
        - qml-module-qtgraphicaleffects
        - qml-module-qtquick-controls
        - qml-module-qtquick-controls2
        - qml-module-qtquick-layouts
        - qml-module-qtquick2
        source: http://download.kde.org/stable/release-service/22.08.3/src/ktouch-22.08.3.tar.xz
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$SNAPCRAFT_STAGE\\;/snap/kde-frameworks-5-100-qt-5-15-7-core20-sd/current"
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/$SNAPCRAFT_ARCH_TRIPLET/6.0.0"
            - "-usr/lib/aspell/*"
            - "-usr/share/lintain"
        prime:
        - "$exclusion"
    cleanup:
        after:
        - ktouch
        plugin: nil
        build-snaps:
        - kde-frameworks-5-99-qt-5-15-7-core20
        override-prime: |
            set -eux
            for snap in "kde-frameworks-5-99-qt-5-15-7-core20"; do  # List all content-snaps you're using here
                cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" "$SNAPCRAFT_PRIME/usr/{}" \;
            done
            find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
            find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
version: 22.08.3
