---
name: ktouch
confinement: strict
grade: stable
base: core20
adopt-info: ktouch
apps:
    ktouch:
        extensions:
        - kde-neon
        common-id: org.kde.ktouch.desktop
        command: usr/bin/ktouch
        plugs:
        - home
        - network
        - network-bind
        - audio-playback
        - removable-media
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    ktouch:
        parse-info:
        - usr/share/metainfo/org.kde.ktouch.appdata.xml
        plugin: cmake
        build-packages:
        - libxcb-xkb-dev
        - libxkbfile-dev
        - libkf5doctools-dev
        stage-packages:
        - qml-module-org-kde-charts
        - libxcb-xkb1
        - libxkbfile1
        - qml-module-org-kde-kcoreaddons
        - qml-module-org-kde-kquickcontrolsaddons
        - qml-module-qtgraphicaleffects
        - qml-module-qtquick-controls
        - qml-module-qtquick-controls2
        - qml-module-qtquick-layouts
        - qml-module-qtquick2
        source: http://download.kde.org/stable/release-service/22.08.0/src/ktouch-22.08.0.tar.xz
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$SNAPCRAFT_STAGE\\;/snap/kde-frameworks-5-96-qt-5-15-5-core20-sdk/current"
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/$SNAPCRAFT_ARCH_TRIPLET/6.0.0"
            - "-usr/lib/aspell/*"
        prime:
        - "$exclusion"
version: 22.08.0
