#!/usr/bin/env bash
# This is the maintainence launcher for the snap, make necessary runtime environment changes to make the snap work here.  You may also insert security confinement/deprecation/obsoletion notice of the snap here.

set \
	-o errexit \
	-o errtrace \
	-o nounset \
	-o pipefail

# gtk-common-themes support
export LIBGL_DRIVERS_PATH=$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/dri"

# Finally run the next part of the command chain
exec "${@}"
