---
name: massif-visualizer
parse-info: massif-visualizer
version: 0.7.0
confinement: strict
grade: stable
base: core20
apps:
    massif-visualizer:
        extensions:
        - kde-neon
        command: massif-visualizer
        plugs:
        - home
        - network
        - network-bind
        - audio-playback
        - removeable-media
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.massif-visualizer
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    massif-visualizer:
        parse-info:
        - usr/share/metainfo/org.kde.massif-visualizer.appdata.xml
        plugin: cmake
        build-packages:
        - libkchart-dev
        - libkgraphviewer-dev
        stage-packages:
        - libkchart
        - libkgraphviewer
        - kgraphviewer
        - valgrind
        source: https://download.kde.org/stable/massif-visualizer/0.7.0/src/massif-visualizer-0.7.0.tar.xz
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;/root/stage\\;/snap/kde-frameworks-5-qt-5-15-3-core20-sdk/current"
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/x86_64-linux-gnu/6.0.0"
            - "-usr/lib/aspell/*"
        prime:
        - "$exclusion"
