---
name: kmplot
confinement: strict
grade: stable
base: core20
adopt-info: kmplot
apps:
    kmplot:
        extensions:
        - kde-neon
        common-id: org.kde.kmplot.desktop
        command: usr/bin/kmplot
        plugs:
        - home
        - network
        - network-bind
        - audio-playback
        - removable-media
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.kmplot
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    kmplot:
        parse-info:
        - usr/share/metainfo/org.kde.kmplot.appdata.xml
        plugin: cmake
        build-packages:
        - libkf5doctools-dev
        source: http://download.kde.org/stable/release-service/22.12.2/src/kmplot-22.12.2.tar.xz
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$SNAPCRAFT_STAGE\\;/snap/kde-frameworks-5-99-qt-5-15-7-core20-sdk/current"
        - "-DKDE_INSTALL_PLUGINDIR=/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/plugins/"
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/$SNAPCRAFT_ARCH_TRIPLET/6.0.0"
            - "-usr/lib/aspell/*"
        prime:
        - "$exclusion"
version: 22.12.2
