---
name: kgeotag
confinement: strict
grade: stable
base: core20
adopt-info: kgeotag
version: 1.2.0
apps:
    kgeotag:
        extensions:
        - kde-neon
        common-id: org.kde.kgeotag
        command: usr/bin/kgeotag
        plugs:
        - home
        - network
        - network-bind
        - audio-playback
        - removable-media
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    kgeotag:
        parse-info:
        - usr/share/metainfo/org.kde.kgeotag.appdata.xml
        plugin: cmake
        build-packages:
        - libkf5kexiv2-dev
        - libmarble-dev
        stage-packages:
        - libmarblewidget-qt5-28
        - libkf5kexiv2-15.0.0
        - libqt5webengine-data
        source: https://download.kde.org/stable/kgeotag/1.2.0/kgeotag-1.2.0.tar.xz
        cmake-parameters:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;/root/stage\\;/snap/kde-frameworks-5-96-qt-5-15-5-core20-sdk/current"
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/x86_64-linux-gnu/6.0.0"
            - "-usr/lib/aspell/*"
        prime:
        - "$exclusion"
