---
name: calligraplan
version: 3.2.2
confinement: strict
grade: stable
base: core20
adopt-info: calligraplan
apps:
    calligraplan:
        common-id: org.kde.calligraplan.desktop
        command: kf5-launch calligraplan
        plugs:
        - kde-frameworks-5-plug
        - home
        - x11
        - opengl
        - network
        - network-bind
        - audio-playback
        - desktop
        - desktop-legacy
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.calligraplan
        bus: session
plugs:
    kde-frameworks-5-plug:
        content: kde-frameworks-5-qt-5-15-core20-all
        interface: content
        default-provider: kde-frameworks-5-qt-5-15-core20
        target: kf5
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    calligraplan:
        parse-info:
        - usr/share/metainfo/org.kde.calligraplan.appdata.xml
        build-snaps:
        - kde-frameworks-5-qt-5-15-core20-sdk
        after:
        - kde-frameworks-5-env
        plugin: cmake
        build-environment:
        - CMAKE_BUILD_PARALLEL_LEVEL: "4"
        build-packages:
        - build-essential
        - qt5-default
        - libkchart-dev
        - libkf5holidays-dev
        - libkf5calendarcore-dev
        - libkf5activities-dev
        - libkf5akonadicontact-dev
        - libkf5contacts-dev
        - libkgantt-dev
        - libqca-qt5-2-dev
        source: http://download.kde.org/stable/calligra/3.2.2/calligraplan-3.2.2.tar.xz
        cmake-parameters:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;/usr\\;/root/stage\\;/snap/kde-frameworks-5-qt-5-15-core20-sdk/current"
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/x86_64-linux-gnu/6.0.0"
            - "-usr/lib/aspell/*"
        prime:
        - "$exclusion"
    kde-frameworks-5-env:
        plugin: dump
        source: https://invent.kde.org/packaging/snap-kf5-launcher.git
