---
name: calligraplan
version: 3.2.2
confinement: strict
grade: stable
base: core20
adopt-info: calligraplan
apps:
    calligraplan:
        extensions:
        - kde-neon
        common-id: org.kde.calligraplan.desktop
        command: usr/bin/calligraplan
        plugs:
        - home
        - network
        - network-bind
        - audio-playback
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.calligraplan
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    calligraplan:
        parse-info:
        - usr/share/metainfo/org.kde.calligraplan.appdata.xml
        plugin: cmake
        build-packages:
        - libkchart-dev
        - libkf5holidays-dev
        - libkf5calendarcore-dev
        - libkf5activities-dev
        - libkf5akonadicontact-dev
        - libkf5contacts-dev
        - libkgantt-dev
        - libqca-qt5-2-dev
        source: http://download.kde.org/stable/calligra/3.2.2/calligraplan-3.2.2.tar.xz
        cmake-parameters:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;/usr\\;$SNAPCRAFT_STAGE\\;/snap/kde-frameworks-5-96-qt-5-15-5-core20-sdk/current"
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/$SNAPCRAFT_ARCH_TRIPLET/6.0.0"
            - "-usr/lib/aspell/*"
        prime:
        - "$exclusion"
