---
name: cantor
confinement: strict
grade: stable
base: core20
adopt-info: cantor
apps:
    cantor:
        common-id: org.kde.cantor.desktop
        command: kf5-launch cantor
        plugs:
        - kde-frameworks-5-plug
        - home
        - x11
        - opengl
        - network
        - network-bind
        - audio-playback
        - desktop
        - desktop-legacy
        - removable-media
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.cantor
        bus: session
plugs:
    kde-frameworks-5-plug:
        content: kde-frameworks-5-qt-5-15-core20-all
        interface: content
        default-provider: kde-frameworks-5-qt-5-15-core20
        target: kf5
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    analitza:
        build-snaps:
        - kde-frameworks-5-qt-5-15-core20-sdk/latest/candidate
        after:
        - kde-frameworks-5-env
        plugin: cmake
        build-environment:
        -   CMAKE_BUILD_PARALLEL_LEVEL: '4'
        build-packages:
        - libncurses-dev
        - libreadline-dev
        - libgl-dev
        - libeigen3-dev
        stage-packages:
        - libncurses6
        - libreadline8
        - libgl1
        - libglx-dev
        source: https://download.kde.org/stable/release-service/20.12.3/src/analitza-20.12.3.tar.xz
        cmake-parameters:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;/root/stage\\;/snap/kde-frameworks-5-qt-5-15-core20-sdk/current"
    cantor:
        build-snaps:
        - kde-frameworks-5-qt-5-15-core20-sdk/latest/candidate
        after:
        - kde-frameworks-5-env
        - analitza
        plugin: cmake
        build-packages:
        - libmarkdown2-dev
        - libglib2.0-dev
        - liblapack-dev
        - libluajit-5.1-dev
        - libqalculate-dev
        - libspectre-dev
        - pkg-config
        - python3-dev
        - r-base-core
        - libjulia-dev
        - libpoppler-dev
        - libpoppler-qt5-dev
        - libkf5doctools-dev
        build-environment:
        -   CMAKE_BUILD_PARALLEL_LEVEL: '4'
        stage-packages:
        - libmarkdown2
        - libglib2.0-0
        - liblapack3
        - libluajit-5.1-2
        - libqalculate20
        - libspectre1
        - python3
        - r-base-core
        - libjulia1
        - libpython3.8
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/x86_64-linux-gnu/6.0.0"
            - "-usr/lib/aspell/*"
        prime:
        - "-var/lib/ghostscript"
        - "-usr/share/ghostscript/*/Resource/CMap"
        - "$exclusion"
        source: http://download.kde.org/stable/release-service/21.08.0/src/cantor-21.08.0.tar.xz
        cmake-parameters:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;/root/stage\\;/snap/kde-frameworks-5-qt-5-15-core20-sdk/current"
        parse-info:
        - usr/share/metainfo/org.kde.cantor.appdata.xml
    kde-frameworks-5-env:
        plugin: dump
        source: https://invent.kde.org/packaging/snap-kf5-launcher.git
