---
name: falkon
confinement: strict
grade: stable
base: core20
version: 22.08.2
adopt-info: falkon
apps:
    falkon:
        extensions:
        - kde-neon
        common-id: org.kde.falkon.desktop
        command: usr/bin/falkon
        plugs:
        - home
        - network
        - network-bind
        - audio-playback
        - browser-support
        - removable-media
        - camera
        - audio-record
layout:
    "/usr/share/qt5":
        symlink: "$SNAP/kf5/usr/share/qt5"
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.Falkon
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    falkon:
        parse-info:
        - usr/share/metainfo/org.kde.falkon.appdata.xml
        source: http://download.kde.org/stable/release-service/22.08.2/src/falkon-22.08.2.tar.xz
        plugin: cmake
        build-packages:
        - libkf5doctools-dev
        - libxcb-util-dev
        - libxcb1-dev
        - libssl-dev
        - libkf5purpose-dev
        - python3-pyside2
        - python3
        stage-packages:
        - libkf5purpose-bin
        - libkf5purpose5
        - python3-pyside2
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$SNAPCRAFT_STAGE\\;/snap/kde-frameworks-5-98-qt-5-15-6-core20-sdk/current"
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/$SNAPCRAFT_ARCH_TRIPLET/6.0.0"
            - "-usr/lib/aspell/*"
        prime:
        - "$exclusion"
    cleanup:
        after:
        - falkon
        plugin: nil
        build-snaps:
        - kde-frameworks-5-98-qt-5-15-6-core20
        override-prime: |
            set -eux
            for snap in "kde-frameworks-5-98-qt-5-15-6-core20"; do  # List all content-snaps you're using here
                cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" "$SNAPCRAFT_PRIME/usr/{}" \;
            done
            find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
