---
name: umbrello
confinement: strict
grade: stable
base: core20
adopt-info: umbrello
version: 22.08.0
apps:
    umbrello:
        extensions:
        - kde-neon
        common-id: org.kde.umbrello.desktop
        command: usr/bin/umbrello5
        plugs:
        - home
        - network
        - network-bind
        - audio-playback
        - removable-media
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.umbrello
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    umbrello:
        parse-info:
        - usr/share/metainfo/org.kde.umbrello.appdata.xml
        plugin: cmake
        build-packages:
        - libxslt1-dev
        - libxml2-dev
        - libboost-dev
        - libkf5doctools-dev
        stage-packages:
        - libboost1.71-dev
        - libxml2
        - libxslt1.1
        source: http://download.kde.org/stable/release-service/22.08.0/src/umbrello-22.08.0.tar.xz
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$SNAPCRAFT_STAGE\\;/snap/kde-frameworks-5-98-qt-5-15-6-core20-sdk/current"
       filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/$SNAPCRAFT_ARCH_TRIPLET/6.0.0"
            - "-usr/lib/aspell/*"
            - "-usr/share/lintain"
        prime:
        - "$exclusion"
    cleanup:
        after:
        - umbrello
        plugin: nil
        build-snaps:
        - kde-frameworks-5-98-qt-5-15-6-core20
        override-prime: |
            set -eux
            for snap in "kde-frameworks-5-98-qt-5-15-6-core20"; do  # List all content-snaps you're using here
                cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" "$SNAPCRAFT_PRIME/usr/{}" \;
            done
            find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
            find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
