---
name: umbrello
confinement: strict
grade: stable
base: core20
adopt-info: umbrello
version: 22.04.3
apps:
    umbrello:
        extensions:
        - kde-neon
        common-id: org.kde.umbrello.desktop
        command: usr/bin/umbrello5
        plugs:
        - home
        - network
        - network-bind
        - audio-playback
        - removable-media
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.umbrello
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    umbrello:
        plugin: cmake
        build-packages:
        - libxslt1-dev
        - libxml2-dev
        - libboost-dev
        - libkf5doctools-dev
        stage-packages:
        - libboost1.71-dev
        - libxml2
        - libxslt1.1
        source: http://download.kde.org/stable/release-service/22.04.3/src/umbrello-22.04.3.tar.xz
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;/root/stage\\;/snap/kde-frameworks-5-91-qt-5-15-3-core20-sdk/current"
        parse-info:
        - usr/share/metainfo/org.kde.umbrello.appdata.xml
