---
name: kgraphviewer
version: 2.4.3
confinement: strict
grade: stable
base: core20
adopt-info: kgraphviewer
apps:
    kgraphviewer:
        extensions:
        - kde-neon
        common-id: org.kde.kgraphviewer.desktop
        command: usr/bin/kgraphviewer
        plugs:
        - home
        - network
        - network-bind
        - audio-playback
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.kgraphviewer
        bus: session
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
    kgraphviewer:
        parse-info:
        - usr/share/metainfo/org.kde.kgraphviewer.appdata.xml
        plugin: cmake
        build-packages:
        - libgraphviz-dev
        - libboost-dev
        - libkf5doctools-dev
        stage-packages:
        - libcdt5
        - libcgraph6
        - libgvc6
        - libltdl7
        - libpathplan4
        source: http://download.kde.org/stable/kgraphviewer/2.4.3/kgraphviewer-2.4.3a.tar.xz
        cmake-parameters:
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;/usr\\;/root/stage\\;/snap/kde-frameworks-5-qt-5-15-3-core20-sdk/current"
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/x86_64-linux-gnu/6.0.0"
            - "-usr/lib/aspell/*"
        prime:
        - "$exclusion"
