---
name: calligra
version: 3.2.1
confinement: strict
grade: stable
base: core20
adopt-info: calligra
apps:
  calligra:
    extensions:
    - kde-neon
    command: usr/bin/calligra
    plugs:
    - home
    - network
    - network-bind
    - audio-playback
    - removable-media
  calligrawords:
    extensions:
    - kde-neon
    common-id: org.kde.calligrawords.desktop
    command: usr/bin/calligrawords
    plugs:
    - home
    - network
    - network-bind
    - audio-playback
    - removable-media
  calligrastage:
    extensions:
    - kde-neon
    common-id: org.kde.calligrastage.desktop
    command: usr/bin/calligrastage
    plugs:
    - home
    - network
    - network-bind
    - audio-playback
    - removable-media
  calligrasheets:
    extensions:
    - kde-neon
    common-id: org.kde.calligrasheets.desktop
    command: usr/bin/calligrasheets
    plugs:
    - home
    - network
    - network-bind
    - audio-playback
    - removable-media
  karbon:
    extensions:
    - kde-neon
    common-id: org.kde.karbon.desktop
    command: usr/bin/karbon
    plugs:
    - kde-frameworks-5-plug
    - home
    - network
    - network-bind
    - audio-playback
    - removable-media
slots:
  session-dbus-interface:
    interface: dbus
    name: org.kde.calligra
    bus: session
parts:
  calligra:
    after:
    - kdelibs4support
    plugin: cmake
    build-packages:
    - libboost-dev
    - libboost-system-dev
    - libeigen3-dev
    - libetonyek-dev
    - libfontconfig1-dev
    - libfreetype6-dev
    - libgit2-dev
    - libgsl-dev
    - libicu-dev
    - libjpeg-dev
    - libkchart-dev
    - libkgantt-dev
    - libkproperty3-dev
    - libkreport3-dev
    - liblcms2-dev
    - libmarble-dev
    - libodfgen-dev
    - libopenexr-dev
    - libopenjp2-7-dev
    - libphonon4qt5-dev
    - libphonon4qt5experimental-dev
    - libpng-dev
    - libpoppler-private-dev
    - libpoppler-qt5-dev
    - libqca-qt5-2-dev
    - libspnav-dev
    - libvisio-dev
    - libwpd-dev
    - libwpg-dev
    - libwps-dev
    - libxbase64-dev
    - libxml2-dev
    - pkg-config
    - pkg-kde-tools
    - pstoedit
    - shared-mime-info
    - zlib1g-dev
    stage-packages:
    - libqca-qt5-2
    - libetonyek-0.1-1
    - libgsl23
    - libgslcblas0
    - libilmbase24
    - libkchart2
    - liblangtag1
    - libodfgen-0.1-1
    - libphonon4qt5experimental4
    - librevenge-0.0-0
    - libspnav0
    - libvisio-0.1-1
    - libwpd-0.10-10
    - libwpg-0.3-3
    - libwps-0.4-4
    parse-info:
    - usr/share/metainfo/org.kde.calligrawords.appdata.xml
    - usr/share/metainfo/org.kde.calligrasheets.appdata.xml
    - usr/share/metainfo/org.kde.calligrastage.appdata.xml
    - usr/share/metainfo/org.kde.karbon.appdata.xml
    source: https://download.kde.org/stable/calligra/3.2.1/calligra-3.2.1.tar.xz
    cmake-parameters:
    - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
    - "-DCMAKE_INSTALL_PREFIX=/usr"
    - "-DCMAKE_BUILD_TYPE=Release"
    - "-DENABLE_TESTING=OFF"
    - "-DBUILD_TESTING=OFF"
    - "-DKDE_SKIP_TEST_SETTINGS=ON"
    - "-DKDE_INSTALL_PLUGINDIR=/usr/lib/x86_64-linux-gnu/qt5/plugins/"
    - "-DCMAKE_FIND_ROOT_PATH=/usr\\;/root/stage\\;/snap/kde-frameworks-5-qt-5-15-core20-sdk/current"
    filesets:
        exclusion:
        - "-usr/lib/*/cmake/*"
        - "-usr/include/*"
        - "-usr/share/ECM/*"
        - "-usr/share/doc/*"
        - "-usr/share/man/*"
        - "-usr/share/icons/breeze-dark*"
        - "-usr/bin/X11"
        - "-usr/lib/gcc/x86_64-linux-gnu/6.0.0"
        - "-usr/lib/aspell/*"
    prime:
    - "$exclusion"
  kdelibs4support:
    plugin: cmake
    build-packages:
    - extra-cmake-modules
    - cmake
    - kgendesignerplugin
    - libintl-perl
    - network-manager-dev
    - libsm-dev
    - libnm-dev
    - libkf5doctools-dev
    - kded5
    source: https://download.kde.org/stable/frameworks/5.79/portingAids/kdelibs4support-5.83.0.tar.xz
    cmake-parameters:
    - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
    - "-DCMAKE_INSTALL_PREFIX=/usr"
    - "-DCMAKE_BUILD_TYPE=Release"
    - "-DENABLE_TESTING=OFF"
    - "-DBUILD_TESTING=OFF"
    - "-DKDE_SKIP_TEST_SETTINGS=ON"
    - "-DCMAKE_FIND_ROOT_PATH=/usr\\;/root/stage\\;/snap/kde-frameworks-5-qt-5-15-core20-sdk/current"
    filesets:
        exclusion:
        - "-usr/lib/*/cmake/*"
        - "-usr/include/*"
        - "-usr/share/ECM/*"
        - "-usr/share/doc/*"
        - "-usr/share/man/*"
        - "-usr/share/icons/breeze-dark*"
        - "-usr/bin/X11"
        - "-usr/lib/gcc/x86_64-linux-gnu/6.0.0"
        - "-usr/lib/aspell/*"
    prime:
    - "$exclusion"
    - "-usr/lib/*/libexec/kf5/fileshareset"
