---
name: calligra
version: 3.2.1
confinement: strict
grade: stable
base: core20
adopt-info: calligra
apps:
  calligra:
    extensions:
    - kde-neon
    command: usr/bin/calligra
    plugs:
    - home
    - network
    - network-bind
    - audio-playback
    - removable-media
  calligrawords:
    extensions:
    - kde-neon
    common-id: org.kde.calligrawords.desktop
    command: usr/bin/calligrawords
    plugs:
    - home
    - network
    - network-bind
    - audio-playback
    - removable-media
  calligrastage:
    extensions:
    - kde-neon
    common-id: org.kde.calligrastage.desktop
    command: usr/bin/calligrastage
    plugs:
    - home
    - network
    - network-bind
    - audio-playback
    - removable-media
  calligrasheets:
    extensions:
    - kde-neon
    common-id: org.kde.calligrasheets.desktop
    command: usr/bin/calligrasheets
    plugs:
    - home
    - network
    - network-bind
    - audio-playback
    - removable-media
  karbon:
    extensions:
    - kde-neon
    common-id: org.kde.karbon.desktop
    command: usr/bin/karbon
    plugs:
    - home
    - network
    - network-bind
    - audio-playback
    - removable-media
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
slots:
  session-dbus-interface:
    interface: dbus
    name: org.kde.calligra
    bus: session
parts:
  patches:
      source: patches
      plugin: dump
      prime:
      - "-*"
  calligra:
    after: [patches]
    plugin: cmake
    build-packages:
    - libboost-dev
    - libboost-system-dev
    - libeigen3-dev
    - libetonyek-dev
    - libfontconfig1-dev
    - libfreetype6-dev
    - libgit2-dev
    - libgsl-dev
    - libicu-dev
    - libjpeg-dev
    - libkchart-dev
    - libkgantt-dev
    - libkproperty3-dev
    - libkreport3-dev
    - libkf5doctools-dev
    - liblcms2-dev
    - libmarble-dev
    - libodfgen-dev
    - libopenexr-dev
    - libopenjp2-7-dev
    - libphonon4qt5-dev
    - libphonon4qt5experimental-dev
    - libpng-dev
    - libpoppler-private-dev
    - libpoppler-qt5-dev
    - libqca-qt5-2-dev
    - libspnav-dev
    - libvisio-dev
    - libwpd-dev
    - libwpg-dev
    - libwps-dev
    - libxbase64-dev
    - libxml2-dev
    - pkg-config
    - pkg-kde-tools
    - pstoedit
    - shared-mime-info
    - zlib1g-dev
    - libkf5calendarcore-dev
    - libkf5akonadi-dev
    - libkf5akonadicontact-dev
    - libkf5contacts-dev
    - okular-dev
    - cauchy-dev
    - qtdeclarative5-dev
    stage-packages:
    - libqca-qt5-2
    - libetonyek-0.1-1
    - libgsl23
    - libgslcblas0
    - libilmbase24
    - libkchart2
    - liblangtag1
    - libodfgen-0.1-1
    - libphonon4qt5experimental4
    - librevenge-0.0-0
    - libspnav0
    - libvisio-0.1-1
    - libwpd-0.10-10
    - libwpg-0.3-3
    - libwps-0.4-4
    - libfontconfig1
    - libcauchy0.0v5
    - libkf5js5
    - libkf5jsapi5
    - libm2mml0.0v5
    - libokular5core9
    parse-info:
    - usr/share/metainfo/org.kde.calligrawords.appdata.xml
    - usr/share/metainfo/org.kde.calligrasheets.appdata.xml
    - usr/share/metainfo/org.kde.calligrastage.appdata.xml
    - usr/share/metainfo/org.kde.karbon.appdata.xml
    source: https://download.kde.org/stable/calligra/3.2.1/calligra-3.2.1.tar.xz
    override-pull: |
         snapcraftctl pull
         patch -p1 < $SNAPCRAFT_STAGE/text.diff
    cmake-parameters:
    - "-DCMAKE_INSTALL_PREFIX=/usr"
    - "-DCMAKE_BUILD_TYPE=Release"
